### ISSUE TITLE
Suggestion for different default values for batch.size, max.buffered.records, and flush.timeout.ms

### ISSUE THREAD

**Issue by zzbennett** [confluentinc/kafka-connect-elasticsearch#136]
Hello. I just spent quite a while tweaking config values for an ES connector in my 0.11.0.1 & 3.3.0 distributed connector deployment. The connector was consuming a large backlog on a topic and was struggling quite a lot with the default configs. 

With these defaults:
```
flush.timeout.ms=10000
max.buffered.events=20000
batch.size=2000
```

Each task would need to flush 10 batches of up to 2000 events at a time, within 10 seconds. Although deployments can vary a lot, in my experience, only very large ES deployments keep up with this rate of indexing. In a typical cluster, it will take longer than 10 seconds for a single thread to flush 20000 events to ES.

This was actually a big problem, because when the tasks tried to consume data at this rate, they would either encounter this exception:

```
org.apache.kafka.connect.errors.ConnectException: Flush timeout expired with unflushed records: 17754
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor.flush(BulkProcessor.java:302)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.flush(ElasticsearchWriter.java:217)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.flush(ElasticsearchSinkTask.java:125)
        at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:117)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:166)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:150)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```
or this exception:
```
[2017-10-21 21:21:11,610] WARN Failed to execute batch 34716 of 500 records, retrying after 100 ms (io.confluent.connect.elasticsearch.bulk.BulkProcessor)
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:48)
        at io.confluent.connect.elasticsearch.BulkIndexingClient.execute(BulkIndexingClient.java:57)
        at io.confluent.connect.elasticsearch.BulkIndexingClient.execute(BulkIndexingClient.java:34)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.execute(BulkProcessor.java:348)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:326)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:312)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

The first exception causes the task to rewind to the last offset for every batch, so the task would be completely stuck, but its status would still say `RUNNING`.  In the case of the second exception, it would retry and then eventually crash.

In the end, I settled on these configs:
```
batch.size=200
max.buffered.records=1500
flush.timeout.ms=10000
```

The lower batch size prevented the SocketTimeoutExceptions, and the smaller `max.buffered.records` allowed the tasks to flush everything before timing out after 10 seconds.   

After this, the connector was able to consume the backlog without timing out or crashing.

Anyways, this is just a friendly suggestion. Every deployment is different and people will have to tweak their own configs. I think with less aggressive default values, folks will run into fewer issues, especially when their ES connectors are catching up with a large backlog.

**Comment by chicagobuss** [comment]
Hi Elizabeth, thanks for this.  Can you share some details of your ES cluster so if we do tweak the defaults we can give people an idea what size cluster they were tested on?

Thanks again for the work put into this suggestion.

**Comment by zzbennett** [comment]
Sure. Initially, the data was going to a 5 shard index, which is the default size for indexes in ES. I bumped up the size of the index to 30 shards, and gave the connector 24 tasks. Still the flushing was not fast enough, so this is when I started tweaking config values in the connector.

The ES cluster has 15 nodes running in AWS, with m4.large instances, so 4 cores, 8GB memory.
