### ISSUE TITLE
kafka streams combine with kafka-connect-elasticsearch throw error 

### ISSUE THREAD

**Issue by gx6121** [confluentinc/kafka-connect-elasticsearch#150]
I`m useing kafka streams to transfor message to anathor topic 

code example :
.through(Serdes.String(), new JsonPOJOSerde<>(NfDnsMessage.class), "dns_test_5");

but when i use kafka-connect-elasticsearch throw this error:

        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:97)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:406)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!

could anyone can help me ????

**Comment by rmoff** [comment]
Looks like you've configured Connect to use AvroConverter, but your topic data is not in Avro.

**Comment by kkonstantine** [comment]
The explanation by @rmoff seems correct. Closing this issue but feel free to re-open if this is not the case.
