### ISSUE TITLE
Tasks not handling schemas with default null values 

### ISSUE THREAD

**Issue by allisonkuo** [confluentinc/kafka-connect-elasticsearch#190]
```
 ERROR WorkerSinkTask{id=xxxxx} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
connect-distributed[31357]: org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
connect-distributed[31357]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:517)
connect-distributed[31357]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
connect-distributed[31357]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
connect-distributed[31357]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
connect-distributed[31357]:         at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
connect-distributed[31357]:         at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
connect-distributed[31357]:         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect-distributed[31357]:         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect-distributed[31357]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect-distributed[31357]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect-distributed[31357]:         at java.lang.Thread.run(Thread.java:748)
connect-distributed[31357]: Caused by: java.lang.NullPointerException
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.DataConverter.preProcessStructValue(DataConverter.java:305)
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.DataConverter.preProcessValue(DataConverter.java:233)
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.DataConverter.preProcessStructValue(DataConverter.java:305)
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.DataConverter.preProcessValue(DataConverter.java:233)
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.DataConverter.preProcessStructValue(DataConverter.java:305)
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.DataConverter.preProcessValue(DataConverter.java:233)
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:112)
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.ElasticsearchWriter.tryGetIndexableRecord(ElasticsearchWriter.java:254)
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:232)
connect-distributed[31357]:         at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:159)
connect-distributed[31357]:         at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
connect-distributed[31357]:         ... 10 more

```

Saw this error when using a schema with an optional field that defaults to null:
example schema: 
```
{
              "name": "MediaStats",
              "type": [
                "null",
                {
                  "type": "record",
                  "name": "MediaStats",
                  "fields": [
                    {
                      "name": "bitrate",
                      "type": "string"
                    },
                    {
                      "name": "bufferFill",
                      "type": "string"
                    },
                    {
                      "name": "vidFrmDiscard",
                      "type": "string"
                    },
                    {
                      "name": "packetsLost",
                      "type": "string"
                    },
                    {
                      "name": "packetsRcvd",
                      "type": "string"
                    },
                    {
                      "name": "overruns",
                      "type": "string"
                    },
                    {
                      "name": "underruns",
                      "type": "string"
                    },
                    {
                      "name": "URI",
                      "type": "string"
                    }
                  ]
                }
              ],
              "default": null
            }
}
```

After some investigation, it appears that this may be a bug found in DataConverter.java in the `preProcessValue()` method. When `value` is null and `preProcessNullValue()` is called, if the schema is optional, `preProcessNullValue()` will return null. However, in `preProcessValue()`, it only returns `result` if it's not null.  Thus, it continues to process the schema although `value` is null, causing the null pointer exception.

Offending code from [master branch:](
https://github.com/confluentinc/kafka-connect-elasticsearch/blob/d3ef73cbe9c3fb7911f17df293cddbe1d3e50f17/src/main/java/io/confluent/connect/elasticsearch/DataConverter.java#L267-L277)
```
Object preProcessValue(Object value, Schema schema, Schema newSchema) {
...
    if (value == null) {
      Object result = preProcessNullValue(schema);
      if (result != null) {
        return result;
      }
    }
...
}
```

The following code is our attempt at resolving the issue:
```
Object preProcessValue(Object value, Schema schema, Schema newSchema) {
...
    if (value == null) {
      Object result = preProcessNullValue(schema);
      return result; // always return result -- the functionality as seen in v3.3.0
    }
...
}
```

**Comment by levzem** [comment]
@allisonkuo this issue has been resolved by #192 and correspondingly will be closing

thank you for pointing this out!
