### ISSUE TITLE
 Missing required configuration "key.converter" which has no default value

### ISSUE THREAD

**Issue by Andreatop90** [confluentinc/kafka-connect-elasticsearch#202]
Hello I have installed this connector but at the starting phase I received this error:
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Missing required configuration "key.converter" which has no default value.
        at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:463)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:453)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
        at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:218)
        at org.apache.kafka.connect.runtime.standalone.StandaloneConfig.<init>(StandaloneConfig.java:42)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:77)

I start in stand-alone mode

**Comment by rhauch** [comment]
You're worker file does not have the necessary properties, including the `key.converter` mentioned in your exception. Be sure to read the [documentation](https://docs.confluent.io/current/connect/userguide.html#configuring-workers) for details.

Closing since this is not a problem with this connector (or the Connect framework for that matter).

**Comment by SureshKrishnaaR** [comment]
Hi Team,

Though i have all the properties proper in my config file my connect-standalone is not started.

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter


Please clarify on what necessary properties are missing here

Note: It was working fine with the same config details in the worker.properties file. After restarting zookeeper and kafka it is not working.

**Comment by aapramesh** [comment]
Please check your worker properties file as first argument
