### ISSUE TITLE
Error while running connect-standalone

### ISSUE THREAD

**Issue by pomy66** [confluentinc/kafka-connect-elasticsearch#212]
I run the below command and got error:

`./bin/connect-standalone config/connect-standalone.properties config/elasticsearch-connect.properties`

The error said java.lang.NoClassDefFoundError: io/searchbox/client/JestClientFactory, which I am sure that the jest-2.4.0.jar was in the plugin.path

Error logs below:
```
[2018-05-23 15:50:13,582] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
java.lang.NoClassDefFoundError: io/searchbox/client/JestClientFactory
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:120)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:119)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:281)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.searchbox.client.JestClientFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 12 more
[2018-05-23 15:50:13,585] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
[2018-05-23 15:50:13,585] INFO Stopping ElasticsearchSinkTask. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:178)

```
My config files are:

```
# config/connect-standalone.properties 
bootstrap.servers=localhost:9092
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
plugin.path=/Users/xxx/confluent-4.1.0/share/java/kafka-connect-elasticsearch

```

```
# config/elasticsearch-connect.properties 
name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=logs
topic.index.map=logs:logs_index
connection.url=http://localhost:9200
type.name=log
key.ignore=true
schema.ignore=true
plugin.path=/Users/xxx/confluent-4.1.0/share/java/kafka-connect-elasticsearch

```

**Comment by rhauch** [comment]
You're `plugin.path` property in `config/connect-standalone.properties ` is not correct. It is:

    plugin.path=/Users/xxx/confluent-4.1.0/share/java/kafka-connect-elasticsearch

but should be:

    plugin.path=/Users/xxx/confluent-4.1.0/share/java

The `/Users/xxx/confluent-4.1.0/share/java/kafka-connect-elasticsearch` directory is called a _plugin directory_, and the _plugin path_ is the set of directories in which Connect can find _plugin directories_.

Also, the `plugin.path` does not belong in your connector configuration (e.g., `config/elasticsearch-connect.properties`). It only goes in the worker configuration.
