### ISSUE TITLE
Invalid document mapping must not be skip

### ISSUE THREAD

**Issue by tchiotludo** [confluentinc/kafka-connect-elasticsearch#219]
When we have a wrong document mapping, the bulk insert will fail (for a good reason).
Kafka connect will retry the document (which was useless BTW but not a hard issue) 
```
[2018-06-08 10:54:33,522] ERROR Encountered an illegal document error when executing batch 2 of 1 records. Error was [{"type":"illegal_argument_exception","reason":"object mapping [basket_detail] can't be changed from nested to non-nested"}] (to ignore future records like this change the configuration property '%s' from '%s' to '%s'). (io.confluent.connect.elasticsearch.bulk.BulkProcessor)

[2018-06-08 10:54:33,211] ERROR Failed to execute batch 3 of 1 records after total of 6 attempt(s) (io.confluent.connect.elasticsearch.bulk.BulkProcessor)
org.apache.kafka.connect.errors.ConnectException: Bulk request failed: [{"type":"illegal_argument_exception","reason":"object mapping [basket_detail] can't be changed from nested to non-nested"}]
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.handleMalformedDoc(BulkProcessor.java:429)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.execute(BulkProcessor.java:383)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:344)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:330)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

After trying x times, it will failed definitively but the consumer will skip it and offset will be increased.
So the document is lost and there is no way to know what document failed.
It think the connect MUST fail in this case

**Comment by purbon** [comment]
Hi @tchiotludo, if you are using a a version of Apache Kafka bigger than 2.0, you can handle this situation by basically enabling the DLQ functionality, more details in https://cwiki.apache.org/confluence/display/KAFKA/KIP-298%3A+Error+Handling+in+Connect.

You can see more details on how to configure this for the sync connectors here ->https://cwiki.apache.org/confluence/display/KAFKA/KIP-298%3A+Error+Handling+in+Connect#KIP-298:ErrorHandlinginConnect-DeadLetterQueue(forSinkConnectorsonly)

What this will basically do, is as soon as the configured retry are exhausted, it will park this document in an specific kafka topic.

With the introduction of error handling, there is as well the capability to tolerate errors build in the framework, In here you can configure the task to either fail or tolerate all errors, see https://cwiki.apache.org/confluence/display/KAFKA/KIP-298%3A+Error+Handling+in+Connect#KIP-298:ErrorHandlinginConnect-TaskToleranceLimits for more details.

If for your use case, the connect must fail,  I would recommend adding ```errors.tolerance=none```.

Is very important that you activate the DLQ, as of the way lucene and elastic search works, this will be very interesting to handle when mapping is wrong.

As well I do recommend you to have time based indexed in elasticsearch, like this if the mapping change, only the timeslot granularity will be affected and effectively in elastic you can query all of them without performance impact. 

Closing this as a non connector related issue. Feel free to reopen if you find specific elasticsearch connector errors, otherwise you're very welcome to post messages to our community either in slack, or the mailing list. More details from https://www.confluent.io/contact-us-thank-you/

Thanks a lot for your help,
