### ISSUE TITLE
Error while parsing tombstone message

### ISSUE THREAD

**Issue by jigs031** [confluentinc/kafka-connect-elasticsearch#231]
Hello All,

I have Mysql => Kafka => ElasticSearch flow, where i ingest realtime mysql data. In case of delete, I am sending tombstone message {ROWKEY:$id, null} to Kafka. 

While consuming tombstone message at Sink, it is throwing below error. I tried by imposing schema on value too, but no success. Could you please assist.

org.apache.kafka.connect.errors.DataException: Only Map objects supported in absence of schema for [copying fields from value to key], found: null
	at org.apache.kafka.connect.transforms.util.Requirements.requireMap(Requirements.java:38)
	at org.apache.kafka.connect.transforms.ValueToKey.applySchemaless(ValueToKey.java:70)
	at org.apache.kafka.connect.transforms.ValueToKey.apply(ValueToKey.java:63)
	at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:38)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:480)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by fabriziofortino** [comment]
@jigs031 records with non-null keys and null value should be ignored by default. Alternatively you can set `behavior.on.null.values` to `delete` (https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/configuration_options.html). This will create an `IndexableRecord` with null payload that should delete the corresponding document in ES (https://github.com/confluentinc/kafka-connect-elasticsearch/blob/a97e2b048253c706bea80aa79aebfaa30a1d0424/src/main/java/io/confluent/connect/elasticsearch/DataConverter.java#L120-L132).

**Comment by levzem** [comment]
Closing this because it was answered. Please reopen if there are follow up questions.
