### ISSUE TITLE
kafka-elasticsearch connector

### ISSUE THREAD

**Issue by ArpitaSheelavant** [confluentinc/kafka-connect-elasticsearch#232]
When I am running the below command ,I am getting NoClassDefFoundError

bin/windows/connect-standalone.bat config/connect-standalone.properties config/connect-file-sink
-1.properties

ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NoClassDefFoundError: io/searchbox/action/Action
at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:120)
at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:281)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.searchbox.action.Action
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 11 more

My config property file,
name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=elasticsearch-test
connection.url=http://localhost:9200
type.name=kafka-connect
key.ignore=true

any reply would be a great help!

**Comment by purbon** [comment]
Are you running the connector with the vanilla Apache Kafka? or with the Confluent Platform?

**Comment by purbon** [comment]
You should keep an eye on your plugin.path directory setup, keep in mind that it should be organise as commented out in the documentation:

```
# Set to a list of filesystem paths separated by commas (,) to enable class loading isolation for plugins
# (connectors, converters, transformations). The list should consist of top level directories that include 
# any combination of: 
# a) directories immediately containing jars with plugins and their dependencies
# b) uber-jars with plugins and their dependencies
# c) directories immediately containing the package directory structure of classes of plugins and their dependencies
# Note: symlinks will be followed to discover dependencies or plugins.
```

if you put all your jars on the main directory it will not work.

closing this issue as this is more of sort of a question, than a bug. Check https://docs.confluent.io/current/connect/userguide.html#common-worker-configs as well as the example config files within every kafka distribution to know more about this documentation.
