### ISSUE TITLE
org.apache.kafka.connect.errors.DataException: Timestamp missing on record

### ISSUE THREAD

**Issue by clojurians-org** [confluentinc/kafka-connect-elasticsearch#235]
i have the "@timstamp" field,but it failed.
i don't know how to set the timestamp field.

```bash
export KAFKA_CONNECT_HOST="10.132.37.201:8083"
export ES_HOST="http://10.132.37.201:9200,http://10.132.37.202:9200,http://10.132.37.203:9200"

export TABLE_NAME="logi_pimp_protal"
curl -X "POST" "http://$KAFKA_CONNECT_HOST/connectors/" \
     -H "Content-Type: application/json" \
     -d $'{
  "name": "elasticsearch_sink_'$TABLE_NAME'",
  "config": {
    "transforms":"routeTS",  
    "transforms.routeTS.type":"org.apache.kafka.connect.transforms.TimestampRouter",  
    "transforms.routeTS.topic.format":"monitor-${timestamp}",  
    "transforms.routeTS.timestamp.format":"YYYYMM",
    "name": "elasticsearch_sink_'$TABLE_NAME'",
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "tasks.max": "1",
    "topics": "'$TABLE_NAME'",
    "schema.ignore": "true",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "key.ignore": "true",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": false,
    "type.name": "type.name=kafkaconnect",
    "connection.url": "'$ES_HOST'"
  }
}'


curl 10.132.37.201:8083/connectors/elasticsearch_sink_logi_pimp_protal/status

org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
        at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:44)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:532)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:490)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Timestamp missing on record: SinkRecord{kafkaOffset=533758, timestampType=CreateTime} ConnectRecord{topic='logi_pimp_protal', kafkaPartition=0, key=null, value={app_name=logi_pimp_protal, @timestamp=2018-09-04T09:33:10.996Z, offset=1808, @metadata={beat=filebeat, topic=logi_pimp_protal, type=doc, version=6.2.4}, ip=10.128.165.149, beat={hostname=site, name=site, version=6.2.4}, prospector={type=log}, source=/was/IBM/WebSphere/AppServer/profiles/AppSrv01/logs/portal-site/SystemOut.log, message=************ Start Display Current Environment ************
WebSphere Platform 8.5.5.2 [ND 8.5.5.2 cf021414.01][IBMJAVA7 7.0.4.1 gm1318.03] running with process name siteCell01\siteNode01\portal-site and process id 1293
Host Operating System is Linux, version 2.6.32-431.el6.x86_64
Java version = 1.6.0, Java Compiler = j9jit26, Java VM name = IBM J9 VM
was.install.root = /was/IBM/WebSphere/AppServer
user.install.root = /was/IBM/WebSphere/AppServer/profiles/AppSrv01
Java Home = /was/IBM/WebSphere/AppServer/java/jre
ws.ext.dirs = /was/IBM/WebSphere/AppServer/java/lib:/was/IBM/WebSphere/AppServer/profiles/AppSrv01/classes:/was/IBM/WebSphere/AppServer/classes:/was/IBM/WebSphere/AppServer/lib:/was/IBM/WebSphere/AppServer/installedChannels:/was/IBM/WebSphere/AppServer/lib/ext:/was/IBM/WebSphere/AppServer/web/help:/was/IBM/WebSphere/AppServer/deploytool/itp/plugins/com.ibm.etools.ejbdeploy/runtime
Classpath = /was/IBM/WebSphere/AppServer/profiles/AppSrv01/properties:/was/IBM/WebSphere/AppServer/properties:/was/IBM/WebSphere/AppServer/lib/startup.jar:/was/IBM/WebSphere/AppServer/lib/bootstrap.jar:/was/IBM/WebSphere/AppServer/lib/jsf-nls.jar:/was/IBM/WebSphere/AppServer/lib/lmproxy.jar:/was/IBM/WebSphere/AppServer/lib/urlprotocols.jar:/was/IBM/WebSphere/AppServer/deploytool/itp/batchboot.jar:/was/IBM/WebSphere/AppServer/deploytool/itp/batch2.jar:/was/IBM/WebSphere/AppServer/java/lib/tools.jar
Java Library path = /was/IBM/WebSphere/AppServer/lib/native/linux/x86_64/:/was/IBM/WebSphere/AppServer/java/jre/lib/amd64/compressedrefs:/was/IBM/WebSphere/AppServer/java/jre/lib/amd64:/was/IBM/WebSphere/AppServer/bin:/was/IBM/WebSphere/AppServer/nulldllsdir:/usr/lib:
Orb Version = IBM Java ORB build orb626ifx-20131212.00 (IX90136+IX90137)
************* End Display Current Environment *************}, timestamp=null, headers=ConnectHeaders(headers=)}
        at org.apache.kafka.connect.transforms.TimestampRouter.apply(TimestampRouter.java:72)
        at org.apache.kafka.connect.runtime.TransformationChain.lambda/run/current-system/sw/bin/bash(TransformationChain.java:44)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
        ... 14 more
,id:0,worker_id:10.132.37.202:8083
```

**Comment by clojurians-org** [comment]
when i remove org.apache.kafka.connect.transforms.TimestampRouter,
the connector will run successfully.

**Comment by clojurians-org** [comment]
add version field to filebeat 6.2.4 to resolve it.
```bash
[larluo@larluo-nixos:~/my-env]$ cat nix.conf/filebeat-6.2.4/filebeat.yml.template 
filebeat.prospectors:
- type: log
  enabled: true
  # paths: ["path/to/file"]
  paths: ${path_arr}
  multiline.pattern: '^${pattern}'
  multiline.negate: true
  multiline.match: after
  fields:
    app_name: "${_id}"
    ip: "${_ip}"
  fields_under_root: true

output.kafka:
  # hosts: ["10.132.37.201:9092", "10.132.37.202:9092", "10.132.37.203:9092"]
  hosts: ${host_arr}
  topic: "${_id}"
  version: 0.11.0.0
```
