### ISSUE TITLE
Connector always looking for a schema

### ISSUE THREAD

**Issue by andrepnh** [confluentinc/kafka-connect-elasticsearch#247]
I have an elasticsearch sink, but the connector task always fails with the following exception:
<pre>
[2018-10-16 11:09:36,961] ERROR WorkerSinkTask{id=elasticsearch-inventory-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
     at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:510)
     at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:490)
     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: JsonConverter with schemas.enable requires "schema" and "payload" fields and may not contain additional fields. If you are trying to deserialize plain JSON data, set schemas.enable=false in your converter configuration.
     at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:338)
     at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$0(WorkerSinkTask.java:510)
     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
     ... 13 more
[2018-10-16 11:09:37,084] ERROR WorkerSinkTask{id=elasticsearch-inventory-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)
</pre>

I do have `schemas.enable` set to false, this is the configuration that the connector rest API returns (notice I've tried different combinations): 
```json
{
  "name": "elasticsearch-inventory-sink",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "type.name": "kafka-connect",
    "key.converter.schemas.enable": "false",
    "tasks.max": "1",
    "topics": "warehouse-capacity,global-stock,global-stock-percentage",
    "name": "elasticsearch-inventory-sink",
    "value.converter.schemas.enable": "false",
    "key.ignore": "false",
    "connection.url": "http://elasticsearch:9200",
    "schema.ignore": "true",
    "schemas.enable": "false"
  },
  "tasks": [
    {
      "connector": "elasticsearch-inventory-sink",
      "task": 0
    }
  ],
  "type": "sink"
}
```

I'm using kafka 2.0.0 with Connect on distributed mode, elasticsearch connector 5.0.0 and elasticsearch 5.2.1. 
OS is Windows 10, with everything running on containers on top of a docker machine.

Am I missing something?

**Comment by purbon** [comment]
The necessary as well config variables to "ignore" schemas are:

```
key.converter.schemas.enable=false
value.converter.schemas.enable=false
```

I was not able to find a better documentation, but you can get this gist from dear @rmoff 
 as reference, https://gist.github.com/rmoff/f32543f78d821b25502f6db49eee9259 

This is less than a bug more of a question, for such things I recommend you to go to the slack community (https://launchpass.com/confluentcommunity) or the mailing lists (https://groups.google.com/forum/#!forum/confluent-platform or https://lists.apache.org/list.html?users@kafka.apache.org ) where you might get a faster answer from not just developers, but as well the overall community.

Hope it help, let me know if I can close this issue.

**Comment by andrepnh** [comment]
I was using those keys, but what I found misleading is that they are global configurations, so setting them on a per connector basis, as I was doing, doesn't work.

Thanks for the help, purbon.

**Comment by purbon** [comment]
fair point and resonable issue that you can not override per connector this config, would you mind raising an issue directly at core kafka https://issues.apache.org/jira/projects/KAFKA/issues/KAFKA-7508?filter=allopenissues, I think is mostly an issue to be tackled there in a general point of view, don't you think?
