### ISSUE TITLE
ES ingest getting failed

### ISSUE THREAD

**Issue by itskannanraj** [confluentinc/kafka-connect-elasticsearch#252]
getting below error when am trying to send raw apache logs

Error: 
org.apache.kafka.connect.errors.ConnectException: Cannot create mapping {"kafka-connect":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}} -- {"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : text] [fields : {keyword={type=keyword, ignore_above=256}}]"}],"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : text] [fields : {keyword={type=keyword, ignore_above=256}}]"}

Environment: 
filebeat -> kafka -> kafka-connect-elasticsearch -> elasticsearch 

Versions : ES 6.4.1 
kafka-connect-elasticsearch : 5.0

conf: 
{
 "name" : "es_sink",
 "config" : {
  "connector.class" : "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "tasks.max" : "10",
  "topics" : "bfaccess",
  "topic.index.map" : "bfaccess:prod",
  "connection.url" : "http://localhost:9200",
  "type.name" : "kafka-connect",
  "schema.ignore" : "false",
 }
}

**Comment by purbon** [comment]
Hi,
  what you are seeing here is not an connector issue, but an error bubble up from the elasticsearch side. Elasticsearch is reporting the impossibility to create a mapping. To fix that I would certainly investigate first manually the sort of events you have and how the schema looks like.

I will close this issue as is not a connector, great sources to discuss such issues and get help of the broader audiences are:

* The confluent community slack: https://launchpass.com/confluentcommunity

In general as well all the confluent community resources that you can found at https://docs.confluent.io/current/resources.html#community

**Comment by faysalmazeddiu** [comment]
hello , I am new of kafka . i want to load string data from kafka topic to elasticsearch  using elasticsearchSink Connector. but I can not , I am getting error . bellow is my code :

**writting data to kafka code :** 

```
final Properties streamsConfiguration = new Properties();
        // unique app id on kafka cluster
        streamsConfiguration.put(StreamsConfig.APPLICATION_ID_CONFIG, "citi-bike-low-availability");
        streamsConfiguration.put(StreamsConfig.CLIENT_ID_CONFIG, "citi-bike-low-availability-client");
        // kafka broker address
        streamsConfiguration.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);
        streamsConfiguration.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");

        streamsConfiguration.put(StreamsConfig.DEFAULT_VALUE_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());
        streamsConfiguration.put(StreamsConfig.DEFAULT_KEY_SERDE_CLASS_CONFIG, Serdes.String().getClass().getName());
 streamsConfiguration.put("schema.registry.url", "http://my-schema-registry:8081");

KStream<String, String> outputStream = statusStream
                .leftJoin(stationInfoTable, (num_bikes, info) -> {
                    return new BikeStats(Integer.parseInt(num_bikes), info.capacity,
                            info.latitude, info.longitude);
                })
                .filter((k, stats) -> stats.availabilityRatio < 0.1)
                .map((k, stats )->{ 
                	try {
                		AfterStreamProcess result=new AfterStreamProcess();
                    	result.stationId=k;
                    	result.longitude=stats.longitude;
                    	result.latitude=stats.latitude;
                    	result.numBikesAvailable=stats.numBikesAvailable;
                    	result.capacity=stats.stationCapacity;	
                    	result.ratio=String.format("%.2f", stats.availabilityRatio * 100) + "%";
                    	//resultList.add(result);
                    	String value=mapper.writeValueAsString(result);
                    	return new KeyValue<>(k,value);
                    } catch (Exception e) {
                        throw new RuntimeException("Output error" + e);
                    }
                });
			
        // output to kafka topic
        outputStream
                .to(LOW_BIKE_TOPIC, Produced.with(Serdes.String(), Serdes.String()));
```

**elastic search sink connector**

```
{
  "name": "es-sink-mysql-foobar-02",
  "config": {
    "_comment": "-- standard converter stuff -- this can actually go in the worker config globally --",
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",

    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    
    "value.converter": "org.apache.kafka.connect.storage.StringConverter",

    "key.converter.schema.registry.url": "http://localhost:8081",
    "value.converter.schema.registry.url": "http://localhost:8081",

    "_comment": "--- Elasticsearch-specific config ---",
    "_comment": "Elasticsearch server address",
    "connection.url": "http://localhost:9200",

    "_comment": "Elasticsearch mapping name. Gets created automatically if doesn't exist  ",
    "type.name": "type.name=hello_mapper",

    "_comment": "Which topic to stream data from into Elasticsearch",
    "topics": "low-bike-availability_2",

    "_comment": "If the Kafka message doesn't have a key (as is the case with JDBC source)  you need to specify key.ignore=true. If you don't, you'll get an error from the Connect task: 'ConnectException: Key is used as document id and can not be null.",
    "key.ignore": "true"
  }
}
```


**error in elasticsearch console :**

```
[2019-01-14T13:30:11,775][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [it_Ok-m] failed to put mappings on indices [[[low-bike-availability_2/yjg4ew4KSFqwms8-_sySZA]]], type [type.name=hello_mapper]
org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [type : text] [fields : {keyword={type=keyword, ignore_above=256}}]
	at org.elasticsearch.index.mapper.DocumentMapperParser.checkNoRemainingFields(DocumentMapperParser.java:151) ~[elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:139) ~[elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.index.mapper.DocumentMapperParser.parse(DocumentMapperParser.java:91) ~[elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.index.mapper.MapperService.parse(MapperService.java:644) ~[elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:264) ~[elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:230) ~[elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:634) ~[elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:612) ~[elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:571) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:575) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) [elasticsearch-5.6.9.jar:5.6.9]
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) [elasticsearch-5.6.9.jar:5.6.9]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

```

**Comment by purbon** [comment]
Hi,
  the error you are seeing here is a mapping problem,

```org.elasticsearch.index.mapper.MapperParsingException: Root mapping definition has unsupported parameters:  [type : text] [fields : {keyword={type=keyword, ignore_above=256}}]
```

it tells you text is not supported for your index version. 

As this is not a product bug, I would recommend you all to check https://launchpass.com/confluentcommunity and ask there for this sort of questions, I'm sure you will find a faster solution in the community.
