### ISSUE TITLE
Kafka ElasticSearch Connector keep restarting 

### ISSUE THREAD

**Issue by Wenbin1982** [confluentinc/kafka-connect-elasticsearch#268]
Background: We are using Kafka ElasticSearch Connector to move data from Kafka to ELS . We are running KEC as a kubernetes POD to connect ElasticSeach(AWS ElasticSearch Service) and Kafka cluster (setup on AWS instances).

Configuration:
  connect-standalone.properties: |-
    bootstrap.servers = 10.1.4.244:9092,10.1.5.170:9092,10.1.6.94:9092,10.1.4.101:9092,10.1.5.207:9092
    key.converter = org.apache.kafka.connect.json.JsonConverter
    value.converter = org.apache.kafka.connect.json.JsonConverter
    schema.ignore = true
    key.converter.schemas.enable = false
    value.converter.schemas.enable = false
    internal.key.converter = org.apache.kafka.connect.json.JsonConverter
    internal.value.converter = org.apache.kafka.connect.json.JsonConverter
    internal.key.converter.schemas.enable = false
    internal.value.converter.schemas.enable = false
    offset.storage.file.filename = /tmp/connect.offsets
    offset.flush.interval.ms = 100000

  elasticsearch-connect.properties: |
    name = elasticsearch-sink
    connector.class = io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
    tasks.max = 1
    topics = *
    topic.index.map = *:events
    connection.url = https://search-***-staging-devnet-es-*********.com
    type.name = events
    key.ignore = true
    schema.ignore = true

Issue Description:
KEC pod keeps restarting and following error was detected .

[2018-12-25 07:12:50,531] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask:450)
[2018-12-25 07:12:50,531] WARN {} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask:302)
[2018-12-25 07:12:50,531] ERROR Commit of WorkerSinkTask{id=elasticsearch-sink-0} offsets threw an unexpected exception:  (org.apache.kafka.connect.runtime.WorkerSinkTask:204)
org.apache.kafka.connect.errors.ConnectException: Bulk request failed: [{"type":"mapper_parsing_exception","reason":"failed to parse [data.bmmap.DEVWKS-2449.metadata.eventEndDate]","caused_by":{"type":"illegal_argument_exception","reason":"Invalid format: \"\""}}]
	at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.execute(BulkProcessor.java:353)
	at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:326)
	at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:312)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2018-12-25 07:12:50,531] ERROR Task elasticsearch-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:451)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[2018-12-25 07:12:50,532] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)
[2018-12-25 07:12:50,532] INFO Stopping ElasticsearchSinkTask. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:135)
[2018-12-25 07:12:50,532] WARN Failed to flush during stop (io.confluent.connect.elasticsearch.ElasticsearchWriter:228)
org.apache.kafka.connect.errors.ConnectException: Bulk request failed: [{"type":"mapper_parsing_exception","reason":"failed to parse [data.bmmap.DEVWKS-2449.metadata.eventEndDate]","caused_by":{"type":"illegal_argument_exception","reason":"Invalid format: \"\""}}]
	at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.execute(BulkProcessor.java:353)
	at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:326)
	at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:312)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lukegil** [comment]
This is a bit old, but it looks like your getting a `mapper_parsing_exception` from Elasticsearch, due to a poorly formatted date. 

My guess is if you look further back in your logs you'll see something like `Failed to execute batch {} of {} records with attempt {}/{}`. The connector should have tried to submit the update [max.retries](https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/configuration_options.html#connector) times (default: 5). Once it received 5 failures, it kills the task. 

Perhaps try running the connector locally with a [higher log-level](https://github.com/confluentinc/kafka-connect-elasticsearch/issues/109). It will print out the bulk requests.

**Comment by jediMunees** [comment]
We can see the following error from your log. What is the data format getting passed to eventEndDate ?
[{"type":"mapper_parsing_exception","reason":"failed to parse [data.bmmap.DEVWKS-2449.metadata.eventEndDate]",

Also, you can use Avro schema format instead of json. With help of schemaRegistery and kafkaConnect, we can have schema based message format. "https://github.com/confluentinc/schema-registry"

**Comment by levzem** [comment]
The above answers are correct, so due to lack of response, closing this issue, but please feel free to reopen if you still need help.
