### ISSUE TITLE
how to use  StringConverter?

### ISSUE THREAD

**Issue by tan00** [confluentinc/kafka-connect-elasticsearch#269]
I am trying to send string data to es

here is part of `etc/schema-registry/connect-avro-standalone.properties`

```
key.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=org.apache.kafka.connect.storage.StringConverter
value.converter.schema.registry.url=http://localhost:8081

key.converter.schemas.enable=false
value.converter.schemas.enable=false
```

part of  `etc/kafka-connect-elasticsearch/quickstart-elasticsearch.properties`
```
schema.ignore=true
```

after send a string msg , such as  `teststring`  or `{"key":"key1" , "name":"Test log", "severity": "INFO"}`  get a exception

```
[2018-12-29 10:51:46,082] ERROR WorkerSinkTask{id=elasticsearch-sink-3} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: Key is used as document id and can not be null.

```
if delete  `schema.ignore=true`, I get some error similar as  #32.

**Comment by cricket007** [comment]
A plain string is a valid JSON object, so have you tried to keep `JSONConverter`?

And how are you sending this data? With `kafka-console-producer`? If so, you need to include the key so it is not null with `--property parse.key=true`

http://bigdatums.net/2017/05/21/send-key-value-messages-kafka-console-producer/

---

Note: 
1. `schemas.enable=(true/false)` only applies to `JSONConverter`
2. `schema.registry.url=(http://...)` only applies to `AvroConverter`

**Comment by tan00** [comment]
`property parse.key=true` worked

Thanks

**Comment by cricket007** [comment]
Welcome. Feel free to close the issue.
