### ISSUE TITLE
Cannot create mapping. Mapping definition … has unsupported parameters (Debezium -> Elasticsearch)

### ISSUE THREAD

**Issue by gp0014** [confluentinc/kafka-connect-elasticsearch#285]
I am using debezium to capture mysql binlog to kafak and kafka-connect-es save data to ES. When my table contains NOT NULL TIMESTAMP field, the ES connect create mapping failed with following error.
```[2019-03-19 16:49:27,377] ERROR WorkerSinkTask{id=elasticsearch-mysql-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:584)
org.apache.kafka.connect.errors.ConnectException: Cannot create mapping {"mysqldata":{"properties":{"id":{"type":"integer"},"update_time":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}},"null_value":"1970-01-01T00:00:00Z"},"name":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}} -- {"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [update_time] has unsupported parameters:  [null_value : 1970-01-01T00:00:00Z]"}],"type":"mapper_parsing_exception","reason":"Mapping definition for [update_time] has unsupported parameters:  [null_value : 1970-01-01T00:00:00Z]"}
        at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createMapping(JestElasticsearchClient.java:254)
        at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:66)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:258)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:162)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-03-19 16:49:27,413] INFO WorkerSinkTask{id=elasticsearch-mysql-sink-0} Committing offsets synchronously using sequence number 1: {mysqlsink.test.test2-1=OffsetAndMetadata{offset=1, metadata=''}, mysqlsink.test.test-1=OffsetAndMetadata{offset=0, metadata=''}, mysqlsink.test.test2-0=OffsetAndMetadata{offset=0, metadata=''}, mysqlsink.test.test-0=OffsetAndMetadata{offset=0, metadata=''}} (org.apache.kafka.connect.runtime.WorkerSinkTask:331)
[2019-03-19 16:49:27,418] ERROR WorkerSinkTask{id=elasticsearch-mysql-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: Cannot create mapping {"mysqldata":{"properties":{"id":{"type":"integer"},"update_time":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}},"null_value":"1970-01-01T00:00:00Z"},"name":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}}} -- {"root_cause":[{"type":"mapper_parsing_exception","reason":"Mapping definition for [update_time] has unsupported parameters:  [null_value : 1970-01-01T00:00:00Z]"}],"type":"mapper_parsing_exception","reason":"Mapping definition for [update_time] has unsupported parameters:  [null_value : 1970-01-01T00:00:00Z]"}
        at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createMapping(JestElasticsearchClient.java:254)
        at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:66)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:258)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:162)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        ... 10 more
```
Here is my table structure
```
CREATE TABLE `test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
This is message which debezium sent to kafka
```
{
	"schema": {
		"type": "struct",
		"fields": [{
			"type": "int32",
			"optional": false,
			"field": "id"
		}, {
			"type": "string",
			"optional": false,
			"name": "io.debezium.time.ZonedTimestamp",
			"version": 1,
			"default": "1970-01-01T00:00:00Z",
			"field": "update_time"
		}, {
			"type": "string",
			"optional": false,
			"field": "name"
		}],
		"optional": true,
		"name": "mysqlsink.test.test.Value"
	},
	"payload": {
		"id": 8,
		"update_time": "2019-03-19T07:02:44Z",
		"name": "ddd"
	}
}
```

ES mapping json
```
{
	"mysqldata": {
		"properties": {
			"id": {
				"type": "integer"
			},
			"update_time": {
				"type": "text",
				"fields": {
					"keyword": {
						"type": "keyword",
						"ignore_above": 256
					}
				},
				"null_value": "1970-01-01T00:00:00Z"
			},
			"name": {
				"type": "text",
				"fields": {
					"keyword": {
						"type": "keyword",
						"ignore_above": 256
					}
				}
			}
		}
	}
}
```

I know the problem is debezium convert the mysql not null timestamp field to string and give the default value to 1970-01-01 00:00:00, so that ES connect put the "null_value": "1970-01-01T00:00:00Z" in a text property.

How can I parse the timestamp field in ES-connect to make the mapping created correctlly?

**Comment by egorzaremba** [comment]
before connect elsticsearch with debezium, you should create an index with mapping

```shell
curl -i -X PUT -H "Accept:application/json" -H  "Content-Type:application/json" http://localhost:9200/users -d @users.json
```

**users.json**
```
{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "_doc": {
      "properties": {
        "id": {
          "type": "integer"
        },
        "update_time": {
          "type": "date"
        },
        "name": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    }
  }
}
```

**Comment by gp0014** [comment]
Thanks for your reply, I have many tables need to be captured, so creating index for each table is not so convenien. Is it possible to give a dynamic mapping to ES-connect, and using this mapping to create indices?

**Comment by rmoff** [comment]
Reopening this as manually creating the mappings is not ideal. 

Recap: 

MySQL column: 

```
CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
```

Debezium's generated schema: 

```
    {
      "name": "CREATE_TS",
      "type": {
        "type": "string",
        "connect.version": 1,
        "connect.default": "1970-01-01T00:00:00Z",
        "connect.name": "io.debezium.time.ZonedTimestamp"
      },
      "default": "1970-01-01T00:00:00Z"
    }
```

Mapping generated by the Elasticsearch sink connector:

```
      "CREATE_TS": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        },
        "null_value": "1970-01-01T00:00:00Z"
      },
```

Elasticsearch rejects this mapping

```
{
  "type": "mapper_parsing_exception",
  "reason": "Mapping definition for [CREATE_TS] has unsupported parameters:  [null_value : 1970-01-01T00:00:00Z]"
}
```

Based on [the docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/text.html), `null_value` is not valid for a `text` datatype, only others (such as [`keyword`](https://www.elastic.co/guide/en/elasticsearch/reference/current/keyword.html))

**Comment by purbon** [comment]
related to #132

**Comment by purbon** [comment]
related to #99

**Comment by rmoff** [comment]
This problem can be sidestepped by setting `"schema.ignore": "true"`, but the target mapping is then created by Elasticsearch based on the data it gets so may or may not match the actual source schema.

**Comment by purbon** [comment]
true, I would focus this issue to the _null-value_ problem. Then another question separate is the timestamp vs string, right?

**Comment by rmoff** [comment]
PR #302  to fix this

**Comment by purbon** [comment]
@rhauch merge the PR fo the null-problem, what do you think now @rmoff ?

**Comment by levzem** [comment]
going to close this because a fix has been merged
