### ISSUE TITLE
Getting below exception when deploying connector with create-key transforms

### ISSUE THREAD

**Issue by girishlalwani2010** [confluentinc/kafka-connect-elasticsearch#321]
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:50)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:292)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.apache.kafka.connect.transforms.ValueToKey.applyWithSchema(ValueToKey.java:85)
	at org.apache.kafka.connect.transforms.ValueToKey.apply(ValueToKey.java:65)
	at org.apache.kafka.connect.runtime.TransformationChain.lambda$apply$0(TransformationChain.java:50)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)

Configuration that I used is to create connector:

 "transforms":"createKey,extractInt",
 "transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
 "transforms.createKey.fields":"domain_id",
 "transforms.extractInt.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
 "transforms.extractInt.field":"domain_id"

**Comment by levzem** [comment]
@girishlalwani2010 please try to provide more information as it helps debug. From first glance, this looks like that your records are missing a field or a schema, so they are not in a proper form

**Comment by levzem** [comment]
closing this due to lack of response but please reopen if you have follow up questions
