### ISSUE TITLE
Kafka Connect fails to publish to elasticsearch

### ISSUE THREAD

**Issue by DhashS** [confluentinc/kafka-connect-elasticsearch#357]
I'm getting an error with the config 

```
{
  "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "type.name": "foobar",
  "offset.flush.interval.ms": "1000",
  "value.converter.schema.registry.url": "http://schemaregistry.service.consul:8081/",
  "tasks.max": "1",
  "errors.tolerance": "all",
  "connection.url": "http://elasticsearch.service.consul:9200",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "topics.regex": ".*-journal",
  "key.converter": "org.apache.kafka.connect.storage.StringConverter"
}
```

resulting in the connctor backtrace 

```
rg.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:587)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: Cannot create mapping {"foobar":{"properties":{"sensorName":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"sensorUUID":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"battery":{"type":"integer"},"gateway":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"rssi":{"type":"integer"},"temperature":{"properties":{"temperature":{"type":"double"},"unit":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}},"sample_epoch":{"type":"date"}}}} -- {"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createMapping(JestElasticsearchClient.java:254)
	at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:66)
	at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:258)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:162)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
	... 10 more
```

The stacktrace proposes a solution, though i'm unclear on how to implement it - or if it's the right one. This connect configuration used to work, and I'm not sure what changed in order for it to fail.

ES 7.3.2 kafka connect 5.3.1

**Comment by DhashS** [comment]
Turned out it was a version mismatch, i wasn't running all components at 5.3.1
