### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/http/conn/socket/LayeredConnectionSocketFactory

### ISSUE THREAD

**Issue by bcashier** [confluentinc/kafka-connect-elasticsearch#358]
When I launch the connector, I am getting this error message:

```
[2019-11-10 00:05:33,532] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)

java.lang.NoClassDefFoundError: org/apache/http/conn/socket/LayeredConnectionSocketFactory
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:122)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.http.conn.socket.LayeredConnectionSocketFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
[2019-11-10 00:05:33,533] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)
[2019-11-10 00:05:33,533] INFO Stopping ElasticsearchSinkTask. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:185)
```

The config file:

```
name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=test-elasticsearch-sink
key.ignore=true
connection.url=http://localhost:9200
type.name=kafka-connect
```

Do you have any solution for this problem please ?

Used to test the latest beta version (5.4.0) and 5.3.1.

##### Kafka Version
Kafka 2.12-2.3.0

**Comment by levzem** [comment]
@bcashier this means that you are using [older dependency version](https://stackoverflow.com/questions/11151519/java-lang-noclassdeffounderror-org-apache-http-conn-scheme-schemesocketfactory) for httpclient. `LayeredConnectionSocketFactory` is only available after 4.1 and you will need to install the correct jar.

**Comment by cricket007** [comment]
Can you please show the steps you followed to build / install the connector?

**Comment by levzem** [comment]
closing due to no response - please feel free to reopen if you still need help
