### ISSUE TITLE
Not able to set document ID when moving data to elastic.

### ISSUE THREAD

**Issue by nvelumani** [confluentinc/kafka-connect-elasticsearch#372]
Hello Team,

I am getting the following error when I am trying to set a value from the JSON string that I pass as a key-value for document id 

[2020-01-07 22:25:12,737] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:559)
org.apache.kafka.connect.errors.ConnectException: Key is used as document id and can not be null.
        at io.confluent.connect.elasticsearch.DataConverter.convertKey(DataConverter.java:82)
        at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:182)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.tryWriteRecord(ElasticsearchWriter.java:291)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:276)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:174)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-01-07 22:25:12,740] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: Key is used as document id and can not be null.
        at io.confluent.connect.elasticsearch.DataConverter.convertKey(DataConverter.java:82)
        at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:182)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.tryWriteRecord(ElasticsearchWriter.java:291)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:276)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:174)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
        ... 10 more
[2020-01-07 22:25:12,741] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:180)
[2020-01-07 22:25:12,742] INFO Stopping ElasticsearchSinkTask (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:190)
[2020-01-07 22:25:12,744] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Member connector-consumer-elasticsearch-sink-0-00092304-2610-4440-aeb6-7dd148b81215 sending LeaveGroup request to coordinator 192.168.1.230:9092 (id: 2147483546 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:879)

my elasticsearch-connect.properties

name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=test-accounts-2
topic.index.map=test-accounts-2:test-accounts-2
connection.url=http://192.168.x.xx:9200
connection.username=xxxxxxx
connection.password=xxxxxxxxxxxxxxxx
type.name=json
key.ignore=false
schema.ignore=true
**"transforms":"createKey,extractInt",
"transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
"transforms.createKey.fields":"unique_id",
"transforms.extractInt.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
"transforms.extractInt.field":"unique_id"**

Example unique_id value "15776632425114023" that has been passed in the JSON string.

full stack trace attached 

[stracktrace.txt](https://github.com/confluentinc/kafka-connect-elasticsearch/files/4032777/stracktrace.txt)

**Comment by levzem** [comment]
@nvelumani 

`org.apache.kafka.connect.errors.ConnectException: Key is used as document id and can not be null`

looks like your transform is working incorrectly or you have some null values in your topic as the key is `null` for some reason. I would make sure your data is non-null and your transforms are working as expected

**Comment by nvelumani** [comment]
Thanks, Lev For the response I tested by sending the below JSON string to make sure that I don't send anything null 
{"unique_id": "15789704181047420", "test_field": "000000023342342342"}

I tried below transforms to pick unique_id as document ID I get the same error in all the cases can you let me know how to validate my transform, please? Thanks in advance.

Transform 1 

"transforms":"createKey,extractInt",
"transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
"transforms.createKey.fields":"unique_id",
"transforms.extractInt.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
"transforms.extractInt.field":"unique_id"

Transform 2

"transforms":"createKey,extractKey",
"transforms.createKey.type":"org.apache.kafka.connect.transforms.ValueToKey",
"transforms.createKey.fields":"unique_id",
"transforms.extractKey.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
"transforms.extractKey.field":"unique_id"

Transform 3

"transforms":"extractKey",
"transforms.extractKey.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
"transforms.extractKey.field":"unique_id"

**Comment by levzem** [comment]
you mentioned that you are sending a JSON string. For the SMTs to work, you need the information to be in a Kafka `Struct` and not a string. See the [documentation](https://docs.confluent.io/current/connect/transforms/extractfield.html#extractfield).

**Comment by nvelumani** [comment]
Thanks, Lev I tried and it does not give that error anymore actually it does not give any error also it does not move to elastic from Kafka queue as well! It is stuck after setting offset to the queue, Any Idea why it is not moving? 

[2020-01-27 15:36:46,903] INFO Started ElasticsearchSinkTask, will ignore records with null values ('behavior.on.null.values') (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:146)
[2020-01-27 15:36:46,903] INFO WorkerSinkTask{id=elasticsearch-sink-0} Sink task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:302)
[2020-01-27 15:36:46,959] WARN [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Error while fetching metadata with correlation id 2 : {test-kafka-1=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient:1051)
[2020-01-27 15:36:46,972] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Cluster ID: rUG-NEJlTBWH6U_sTYRQrA (org.apache.kafka.clients.Metadata:261)
[2020-01-27 15:36:46,974] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Discovered group coordinator 192.168.1.230:9092 (id: 2147483546 rack: null) (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:728)
[2020-01-27 15:36:46,982] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Revoking previously assigned partitions [] (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:476)
[2020-01-27 15:36:46,983] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:505)
[2020-01-27 15:36:47,016] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] (Re-)joining group (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:505)
[2020-01-27 15:36:47,091] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Successfully joined group with generation 90 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:469)
[2020-01-27 15:36:47,104] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Setting newly assigned partitions: test-kafka-1-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:283)
[2020-01-27 15:36:47,131] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Found no committed offset for partition test-kafka-1-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:989)
[2020-01-27 15:36:47,151] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Resetting offset for partition test-kafka-1-0 to offset 0. (org.apache.kafka.clients.consumer.internals.SubscriptionState:352)
[2020-01-27 15:36:47,159] INFO Index 'test-kafka-1' not found in local cache; checking for existence (io.confluent.connect.elasticsearch.jest.JestElasticsearchClient:299)
[2020-01-27 15:36:47,166] INFO Index 'test-kafka-1' exists in Elasticsearch; adding to local cache (io.confluent.connect.elasticsearch.jest.JestElasticsearchClient:305)
[2020-01-27 15:38:45,909] INFO WorkerSinkTask{id=elasticsearch-sink-0} Committing offsets asynchronously using sequence number 2: {test-kafka-1-0=OffsetAndMetadata{offset=15, leaderEpoch=null, metadata=''}} (org.apache.kafka.connect.runtime.WorkerSinkTask:345)

**Comment by nvelumani** [comment]
Any help is appreciated, Thanks.

**Comment by nvelumani** [comment]
When I changed the Logging level from INFO to TRACE I got to know Below Information! where the DEBUG states  "previous request to 192.168.1.230:9092 (id: 101 rack: null) has not been processed (org.apache.kafka.clients.consumer.internals.Fetcher)" 

what reasons could it have for not getting processed is there a version restriction that I should try ? 


[2020-02-05 22:37:47,521] DEBUG [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Built incremental fetch (sessionId=440680197, epoch=79) for node 101. Added (), altered (), removed () out of (test-kafka-1-0) (org.apache.kafka.clients.FetchSessionHandler)
[2020-02-05 22:37:47,521] DEBUG [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Sending READ_UNCOMMITTED IncrementalFetchRequest(toSend=(), toForget=(), implied=(test-kafka-1-0)) to broker 192.168.1.230:9092 (id: 101 rack: null) (org.apache.kafka.clients.consumer.internals.Fetcher)
[2020-02-05 22:37:47,521] TRACE [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Sending FETCH {replica_id=-1,max_wait_time=500,min_bytes=1,max_bytes=52428800,isolation_level=0,session_id=440680197,session_epoch=79,topics=[],forgotten_topics_data=[],rack_id=} with correlation id 101 to node 101 (org.apache.kafka.clients.NetworkClient)
[2020-02-05 22:37:47,523] TRACE [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Skipping fetch for partition test-kafka-1-0 **because previous request to 192.168.1.230:9092 (id: 101 rack: null) has not been processed** (org.apache.kafka.clients.consumer.internals.Fetcher)
[2020-02-05 22:37:48,024] TRACE [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Completed receive from node 101 for FETCH with correlation id 101, received {throttle_time_ms=0,error_code=0,session_id=440680197,responses=[]} (org.apache.kafka.clients.NetworkClient)
[2020-02-05 22:37:48,024] DEBUG [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Node 101 sent an incremental fetch response for session 440680197 with response=(), implied=(test-kafka-1-0) (org.apache.kafka.clients.FetchSessionHandler)
[2020-02-05 22:37:48,025] DEBUG [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Added READ_UNCOMMITTED fetch request for partition test-kafka-1-0 at position FetchPosition{offset=15, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=192.168.1.230:9092 (id: 101 rack: null), epoch=-1}} to node 192.168.1.230:9092 (id: 101 rack: null) (org.apache.kafka.clients.consumer.internals.Fetcher)

**Comment by levzem** [comment]
> Thanks, Lev I tried sending information in Kafka struct and it does not give that error anymore actually it does not give any error also it does not move to elastic from Kafka queue as well! It is stuck after setting offset to the queue, Any Idea why data is not moving?
> 
> Example record that I am currently sending to the Kafka queue : null {"unique_id " :{"int" :15792978561296882},"test_field": "2019-08-02T20:00:00ZZ"}

@nvelumani can you turn on `DEBUG` for the connect package? That might shed more light on to what is going on. Otherwise, I currently cannot tell why it is not writing anything. Have you checked Elastic to make sure? I am also unsure of what you are sending to Kafka. Is that supposed to be a `null` key?

**Comment by nvelumani** [comment]
If I try to send with out null as " {"unique_id " :{"int" :15792978561296882},"test_field": "2019-08-02T20:00:00ZZ"} " It gives me the below error 
[connect-worker-trace.log](https://github.com/confluentinc/kafka-connect-elasticsearch/files/4181415/connect-worker-trace.log)
[connect-worker-trace.log](https://github.com/confluentinc/kafka-connect-elasticsearch/files/4181417/connect-worker-trace.log)


 ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:559)
org.apache.kafka.connect.errors.ConnectException: Key is used as document id and can not be null.
        at io.confluent.connect.elasticsearch.DataConverter.convertKey(DataConverter.java:82)
        at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:182)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.tryWriteRecord(ElasticsearchWriter.java:291)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:276)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:174)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-02-10 09:24:30,823] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:179)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:561)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: Key is used as document id and can not be null.
        at io.confluent.connect.elasticsearch.DataConverter.convertKey(DataConverter.java:82)
        at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:182)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.tryWriteRecord(ElasticsearchWriter.java:291)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:276)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:174)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:539)
        ... 10 more

Also, I flowed the same structure given in the below link https://docs.confluent.io/current/connect/transforms/valuetokey.html?_ga=2.187137320.1094074311.1581344836-1993013487.1578506923&_gac=1.217277730.1581104482.EAIaIQobChMI-_TPkZnA5wIVD5SzCh2CaQU1EAAYASAAEgKsHfD_BwE#valuetokey

I have attached TRACE level log, when I send the massage in following sturcture 
null {"unique_id " :{"int" :15792978561296882},"test_field": "2019-08-02T20:00:00ZZ"}

**Comment by levzem** [comment]
just from looking at your logs I see

```
[2020-02-10 09:45:17,931] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Polling returned 15 messages (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,934] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 0 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,971] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 0 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,972] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 1 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,972] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 1 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,972] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 2 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,972] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 2 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,972] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 3 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,972] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 3 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,972] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 4 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,972] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 4 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,972] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 5 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 5 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 6 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 6 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 7 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 7 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 8 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 8 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 9 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 9 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 10 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 10 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 11 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,973] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 11 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,974] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 12 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,974] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 12 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,974] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 13 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,974] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 13 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,974] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Consuming and converting message in topic 'test-kafka-3' partition 0 at offset 14 and timestamp -1 (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,974] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Applying transformations to record in topic 'test-kafka-3' partition 0 at offset 14 and timestamp null with key null and value null (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,974] TRACE WorkerSinkTask{id=elasticsearch-sink-0} Delivering batch of 15 messages to task (org.apache.kafka.connect.runtime.WorkerSinkTask)
[2020-02-10 09:45:17,974] DEBUG Putting 15 records to Elasticsearch (io.confluent.connect.elasticsearch.ElasticsearchSinkTask)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/0 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/1 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/2 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/3 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/4 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/5 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/6 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/7 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/8 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/9 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/10 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/11 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/12 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/13 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-02-10 09:45:17,975] TRACE Ignoring sink record with null value for topic/partition/offset test-kafka-3/0/14 (io.confluent.connect.elasticsearch.ElasticsearchWriter)
```

looks like your transforms are not configured correctly or the records have null values, thus the connector is ignoring `null` keys

**Comment by levzem** [comment]
@nvelumani were you able to resolve the issue?

**Comment by levzem** [comment]
closing but feel free to reopen if the issue persists

**Comment by pkgonan** [comment]
@levzem 
@nvelumani 


Hi
How can i filter out records which key is null.
The Filter does not work.
How can i use it ? Is there any sample code about that ?


[ElasticSearch Connector Log]
```
[2020-09-11 04:25:48,896] ERROR Can't convert record from topic/partition/offset cdc-test.First/1/794417. Error message: Key is used as document id and can not be null. (io.confluent.connect.elasticsearch.ElasticsearchWriter)
```


[Kafka-Console-Consuler]
```
kafka-console-consumer --topic cdc-test --bootstrap-server  localhost:9092 --property print.key=true --property print.value=true
```

[Kafka-Console-Consumer Result]
```
Key | Value
null | {"userId":975,"name":"ki","age":"34343"}
```

[Script File]
```
{
  "name": "azar_db_elasticsearch_sink_connector",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "tasks.max": "1",
    "topics.regex": "*",
    "connection.url": "localhost:9092",
    "transforms": "keyNameFilter,keySizeFilter,extract",
    "transforms.keyNameFilter.type": "io.confluent.connect.transforms.Filter$Key",
    "transforms.keyNameFilter.filter.condition": "[?(@.id != null)]",
    "transforms.keyNameFilter.filter.type": "include",
    "transforms.keyNameFilter.missing.or.null.behavior": "exclude",
    "transforms.keySizeFilter.type": "io.confluent.connect.transforms.Filter$Key",
    "transforms.keySizeFilter.filter.condition": "[?(@.length() == 1)]",
    "transforms.keySizeFilter.filter.type": "include",
    "transforms.keySizeFilter.missing.or.null.behavior": "exclude",
    "transforms.extract.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
    "transforms.extract.field": "id",
    "connection.compression": "true",
    "linger.ms": "100",
    "key.ignore": "false",
    "schema.ignore": "true",
    "write.method": "upsert",
    "behavior.on.null.values": "delete",
    "behavior.on.malformed.documents": "ignore",
    "errors.tolerance": "all",
    "type.name": "_doc",
    "drop.invalid.message": "true"
  }
}
```

**Comment by levzem** [comment]
@pkgonan you need a SMT to filter out the null keys, you are currently filtering on length and if `key.id != null`
