### ISSUE TITLE
WorkerSinkTask{id=es-sink-events-0} Task threw an uncaught and unrecoverable exception

### ISSUE THREAD

**Issue by patsadow2** [confluentinc/kafka-connect-elasticsearch#378]
Yestarday it was working correctly today i have something like that. It just stopped to work from day to day.... I am sure that i don't use the latest or anything like that. I lost 4hours and i could find anything. It's not SSL/HTTPS connection.

```
{
	  "name": "es-sink-events",
	  "config": {
		"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
		"tasks.max": "1",
		"topics": "createdevent",
		"connection.url": "http://elasticsearch:9200",
		"transforms": "unwrap,key",
		"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
		"transforms.unwrap.drop.tombstones": "false",
		"transforms.unwrap.drop.deletes": "false",
		"transforms.key.type": "org.apache.kafka.connect.transforms.ExtractField$Key",
		"transforms.key.field": "id",
        "key.ignore": "true",
        "schema.ignore": "true",
		"type.name": "_doc",
		"behavior.on.null.values": "delete"
	  }
}

```

```
2020-01-27 18:19:07,352 ERROR  ||  WorkerSinkTask{id=es-sink-events-0} Task threw an uncaught and unrecoverable exception   [org.apache.kafka.connect.runtime.WorkerTask]
java.lang.NoClassDefFoundError: io/searchbox/action/Action
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:122)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.searchbox.action.Action
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 11 more
2020-01-27 18:19:07,353 ERROR  ||  WorkerSinkTask{id=es-sink-events-0} Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
2020-01-27 18:19:07,353 INFO   ||  Stopping ElasticsearchSinkTask   [io.confluent.connect.elasticsearch.ElasticsearchSinkTask]
```

**Comment by patsadow2** [comment]
It's so iritaiting i lost almost 30hours on that sh***t

**Comment by tirelibirefe** [comment]
@patsadow2 were you able to fix the problem? I have a similar problem.

[https://stackoverflow.com/questions/62015340/elasticsearch-connector-doesnt-work-java-lang-noclassdeffounderror-com-googl](https://stackoverflow.com/questions/62015340/elasticsearch-connector-doesnt-work-java-lang-noclassdeffounderror-com-googl)

**Comment by IqraSami** [comment]
@iXmonvi33 @tirelibirefe How did you remove that error? I have a similar problem.
