### ISSUE TITLE
Tasks are not created

### ISSUE THREAD

**Issue by M3yo** [confluentinc/kafka-connect-elasticsearch#383]
Hello, 

We use kafka-connect to send data from a topic to ElasticSearch.
(Almost) Every morning, the connector doesn't work.

When I check the API, my connector is present, but 0 tasks are running, therefore the connector does "nothing" :
```{
  "name": "myConnector",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "type.name": "myView",
    "behavior.on.null.values": "delete",
    "tasks.max": "2",
    "topics": "mytopic",
    "drop.invalid.message": "true",
    "key.ignore": "false",
    "schema.ignore": "true",
    "behavior.on.malformed.documents": "warn",
    "topic.index.map": "mytopic:myindex",
    "value.converter.schemas.enable": "false",
    "name": "myConnector",
    "connection.url": "http://elasticsearch:9200",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter"
  },
  "tasks": [],
  "type": "sink"
}
```

the /status endpoint shows no errors. but still no tasks:
```
{
  "name": "myConnector",
  "connector": {
    "state": "RUNNING",
    "worker_id": "100.105.89.94:8083"
  },
  "tasks": [],
  "type": "sink"
}
```
No errors are shown in the logs of the kafka-connect worker, at this point we have to delete the connector and re-create it every morning. Then tasks are usually created in the process, until the next day or so when the tasks seem to disapear.

Second problem, which might be related to the first one.
When ElasticSearch goes down, my tasks are in "error" (connection refused to the elastic search node), which is normal. But after ElasticSearch is back online, my tasks are still in the same error state. Here too I need to manually delete/re-create the connector to restore his tasks.

Is there some kind of retry mecanism which recreate tasks in error ? The documentation only mention  "request retry" which is not the same.

**Comment by levzem** [comment]
Hi @M3yo,

1. Do you `DEBUG` or `TRACE` logging enable? That would be good to see. Tasks just disappearing is very strange. It could be a Connect issue.
2. You can restart connectors instead of deleting and recreating. 
3. There is not task retry mechanism. Once a task tries and retries a write and eventually fails, it will permanently go into a failed state until the connector is restarted. If you want to make it more robust to ES going down, increase the retry configurations

**Comment by M3yo** [comment]
After more digging, I've found that my Kafka-connect instance starts right before my elasticsearch instance.

This leads to my connector unable to start 

```[2020-02-24 04:10:53,597] ERROR WorkerSinkTask{id=myConnector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Couldn't start ElasticsearchSinkTask due to connection error:
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:149)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:116)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:122)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:191)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to elasticsearch:9200 [elasticsearch/100.66.64.44] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:150)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:118)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:57)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.getServerVersion(JestElasticsearchClient.java:170)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:147)
```

So my connector is in a weird state where the connector is Running, but no tasks are running. The connector /status page shows no error... but isn't acutally working. 

```
{"name":"myConnector","connector":{"state":"RUNNING","worker_id":"100.97.44.4:8083"},"tasks":[],"type":"sink"}
```
Restarting the connector does nothing (as no tasks are present), the only thing working is to change the "tasks.max" to create the missing tasks. Is this the normal behavior ?

I'm using kafka-connect-elasticsearch 5.1.3 and cp-kafka-connect 5.1.3

**Comment by M3yo** [comment]
After more and more digging in the source code of kafka-connect, it appears that some of my connectors were classified as "inconsistent".

During startup kafka-connects reads all connectors configurations in the "config-storage-topic" and start them all. But if the connector configuration is not complete, the connector will be treated as "inconsistent" and will be let aside until the configuration is updated (through the API).

And we found out that our configuration topic was on 10 partition where the documentation explicitly says :
- config.storage.topic: 1 partition, cleanup.policy=compact

This causes kafka-connect to reads bits of configuration accros many partition and leading to an inconsistent configuration, and my connector was inactive -> present, but 0 tasks associated.

**Comment by levzem** [comment]
Glad you got this resolved!
