### ISSUE TITLE
type.name option causing trouble with elasticsearch 7.6

### ISSUE THREAD

**Issue by devkev16** [confluentinc/kafka-connect-elasticsearch#389]
Hello,

I am not able to get the connector working with elasticseach 7.6. As I know mapping types have been deprecated since elasticsearch 7, but there is still a type.name which is mandatory - this leads to errors when using the sink connector.

I created a sink with the following configuration

```
{
    "name": "quickstart-elasticsearch-sink",
    "config": {
        "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
        "tasks.max": 1,
        "connection.url": "http://elasticsearch:9200",
        "name": "quickstart-elasticsearch-sink",
        "key.ignore": "true",
        "type.name": "_doc",
        "topics": "quickstart-jdbc-users"
    }
}
```
After a few seconds this gives me the following stack trace:
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:586)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)\nCaused by: org.apache.kafka.connect.errors.ConnectException: Cannot create mapping {\"_doc\":{\"properties\":{\"id\":{\"type\":\"integer\"},\"name\":{\"type\":\"text\",\"fields\":{\"keyword\":{\"type\":\"keyword\",\"ignore_above\":256}}},\"created\":{\"type\":\"date\"},\"modified\":{\"type\":\"date\"}}}} -- {\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true.\"}
at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createMapping(JestElasticsearchClient.java:255)
at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:67)
at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:260)
at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:163)
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
... 10 more\n
```

I also tried setting the type.name option to "" (empty string), but this is 1 to 1 reflected in the mapping request the connector is making - it seems there is no option to omit the type at all.

I am using docker with confluent-kafka, confluent-connect and so on, the docker-compose is as follows (note: This is just a playground setup, but I appreciate any suggestions to do better):

```
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
  
  kafka:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 127.0.0.1:29092:29092
      
  schema-registry:
    image: confluentinc/cp-schema-registry:5.0.0
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:32181"
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: "http://schema-registry:8081"

  connect:
    image: confluentinc/cp-kafka-connect:5.0.0
    depends_on:
      - kafka
      - mysql
      - elasticsearch
      - schema-registry
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka:29092"
      CONNECT_REST_PORT: 28083
      CONNECT_GROUP_ID: "quickstart-jdbc-source"
      CONNECT_CONFIG_STORAGE_TOPIC: "quickstart-jdbc-source-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "quickstart-jdbc-source-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "quickstart-jdbc-source-storage"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
      CONNECT_PLUGIN_PATH: "/usr/share/java,/etc/kafka-connect/jars"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "DEBUG"
      CONNECT_LOG4J_LOGGERS: "org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR"
    ports:
      - 127.0.0.1:28083:28083
    volumes:
      - ./jars:/etc/kafka-connect/jars
  
  mysql:
    image: mysql:8.0
    hostname: "mysql-server"
    command: --default-authentication-plugin=mysql_native_password
    ports: 
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kafka

  elasticsearch:
    image: elasticsearch:7.6.0
    environment:
      discovery.type: "single-node"
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:9300:9300
```

The users table which is streamed into kafka is created using the following sql:
```
create table users (
id int NOT NULL AUTO_INCREMENT, 
name varchar(255),
created timestamp DEFAULT CURRENT_TIMESTAMP , 
modified timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP,
CONSTRAINT primary_key PRIMARY KEY (id) 
);
```

The jdbc source-connector is configured as follows:
```
{
    "name": "quickstart-jdbc-source",
    "config": {
        "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
        "tasks.max": 1,
        "connection.url": "jdbc:mysql://mysql:3306/kafka?user=root&password=root",
        "mode": "timestamp+incrementing",
        "incrementing.column.name": "id",
        "timestamp.column.name": "modified",
        "table.whitelist": "users",
        "topic.prefix": "quickstart-jdbc-",
        "poll.interval.ms": 1000
    }
}
```

I verified the source-connector is working using the avro-console-consumer.

I installed the latest version of the kafka-elasticsearch-connector using confluent-hub with this command: `confluent-hub install confluentinc/kafka-connect-elasticsearch:latest`

This installed the version 5.4.0: `Downloading component Kafka Connect Elasticsearch 5.4.0, provided by Confluent, Inc. from Confluent Hub and installing into /usr/share/confluent-hub-components `

Can someone tell me if there is a possibility to omit the type when the connector updates the index mapping or if there is any workaround? (I read the issues concerning elasticsearch 7 but as I understood the problem should be solved in connector versions newer than oder equal to 5.3).

**Comment by devkev16** [comment]
Finally figured out what caused the problem: As I jused confluentinc/cp-kafka-connect:5.0.0 image and not the connect base image it comes bundled with kafka-connect-elasticsearch:5.0.0 .The call to confluent-hub installed the elasticsearch-connector:5.4.0 but the already bundled one (5.0.0) was not removed.

The fix for my dev playground was as follows:
1. Go into the container with bash
2. `cd /usr/share/java`
3. `rm -rf kafka-connect-elasticsearch`
4. `confluent-hub install confluentinc/kafka-connect-elasticsearch:latest`
5. Specify `/usr/share/java` as install dir
6. `docker-compose restart connect`

Now it creates the index + mapping and indexes the documents when you specify `type.name: "_doc"`.

Note that this is just a dev workaround to proof it works. The clean solution is to create an image extending `confluentinc/cp-kafka-connect-base` and including the confluent-hub call as a RUN command or provide a local version of the connector.

**Comment by rmoff** [comment]
For future Googlers: `type.name` is deprecated and was [removed from Kafka Connect Elasticsearch connector from version 11 onwards](https://docs.confluent.io/kafka-connect-elasticsearch/current/changelog.html#version-11-0-0).
