### ISSUE TITLE
Cannot create mapping + Root mapping definition has unsupported parameters

### ISSUE THREAD

**Issue by dkirrane** [confluentinc/kafka-connect-elasticsearch#395]
I'm hitting the following errors with an Elasticsearch Sink Connector.
It's consuming from an Avro topic.

**Kafka Connect Error**
```
[2020-03-02 17:41:16,838] ERROR WorkerSinkTask{id=es-sink1-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.ConnectException: Cannot create mapping {"_doc":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}} -- {"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : text] [fields : {keyword={ignore_above=256, type=keyword}}]"}],"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : text] [fields : {keyword={ignore_above=256, type=keyword}}]"}
        at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createMapping(JestElasticsearchClient.java:317)
        at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:66)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:260)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:169)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-03-02 17:41:16,839] ERROR WorkerSinkTask{id=es-sink1-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:321)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: Cannot create mapping {"_doc":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}} -- {"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : text] [fields : {keyword={ignore_above=256, type=keyword}}]"}],"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [type : text] [fields : {keyword={ignore_above=256, type=keyword}}]"}
        at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createMapping(JestElasticsearchClient.java:317)
        at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:66)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:260)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:169)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:538)
        ... 10 more
[2020-03-02 17:41:16,839] ERROR WorkerSinkTask{id=es-sink1-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
```

**Comment by dkirrane** [comment]
Okay. looks like the first issue was because my index template was missing.
After adding the template, now I'm hitting this error:

```
[2020-03-02 17:20:06,056] ERROR Can't convert record from topic my-topic-202003 with partition 0 and offset 0. Error message: Invalid type for STRING: class org.apache.kafka.connect.data.Struct (io.confluent.connect.elasticsearch.ElasticsearchWriter)
```

**Comment by levzem** [comment]
@dkirrane more logs would be helpful. Turning on `TRACE` can also provide beneficial information. 

Do you have records with keys of type `Struct` in your topic? The `StringConverter` cannot be used to deserialize them.

**Comment by dkirrane** [comment]
My key is a String.
The value is an Avro SpecificRecords. It does have a field of type `map` and a field of type array of type `record`. 
I'll see if I can dig out how to enable KC trace.

**Comment by dkirrane** [comment]
@levzem Here's logs with `TRACE`
```
[2020-03-02 23:35:33,896] INFO [Consumer clientId=consumer-5, groupId=connect-es-sink1] Resetting offset for partition engagement-aggregate-0 to offset 0. (org.apache.kafka.clients.consumer.internals.Fetcher)
[2020-03-02 23:35:33,896] DEBUG Opening the task for topic partitions: [engagement-aggregate-0] (io.confluent.connect.elasticsearch.ElasticsearchSinkTask)
[2020-03-02 23:35:33,896] DEBUG Topic 'engagement-aggregate' was translated as index 'engagement-aggregate' (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-03-02 23:35:34,041] DEBUG Sending GET with input null to http://kafka-cp-schema-registry:8081/schemas/ids/1 (io.confluent.kafka.schemaregistry.client.rest.RestService)
[2020-03-02 23:35:34,063] DEBUG Sending GET with input null to http://kafka-cp-schema-registry:8081/schemas/ids/1 (io.confluent.kafka.schemaregistry.client.rest.RestService)
[2020-03-02 23:35:34,081] DEBUG Sending POST with input {"schema":"{\"type\":\"record\",\"name\":\"EngagementAggregate\",\"namespace\":\"com.company.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"tenantId\",\"type\":\"string\"},{\"name\":\"identifiers\",\"type\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"string\",\"java-class\":\"java.util.HashSet\"}},\"default\":{}},{\"name\":\"conversations\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Conversation\",\"fields\":[{\"name\":\"intent\",\"type\":\"string\"},{\"name\":\"startedAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"doc\":\"Timestamp (milliseconds since epoch) the conversation started at on the engagement\",\"default\":null}]}},\"default\":[]},{\"name\":\"participants\",\"type\":{\"type\":\"array\",\"items\":[{\"type\":\"record\",\"name\":\"ExternalParticipant\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"the unique identifier for the external participant\"},{\"name\":\"callingNumber\",\"type\":\"string\",\"doc\":\"the calling number of the external participant\"},{\"name\":\"dialledNumber\",\"type\":\"string\",\"doc\":\"the original dialled number for the engagement\"},{\"name\":\"providerCallId\",\"type\":\"string\",\"doc\":\"the provider-native identifier for the call\"},{\"name\":\"channelType\",\"type\":{\"type\":\"enum\",\"name\":\"ChannelType\",\"symbols\":[\"VOICE\",\"VIDEO\"]},\"doc\":\"the channelType of the engagement\"},{\"name\":\"joinedAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"doc\":\"Timestamp (milliseconds since epoch) the external participant joined the engagement\",\"default\":null},{\"name\":\"leftAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"doc\":\"Timestamp (milliseconds since epoch) the external participant left the engagement\",\"default\":null}]},{\"type\":\"record\",\"name\":\"AutomationParticipant\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"the identifier for the automation participant\"},{\"name\":\"channelProviderId\",\"type\":\"string\",\"doc\":\"the unique identifier for this engagement provider\"},{\"name\":\"providerDialogId\",\"type\":\"string\",\"doc\":\"the channelProviders identifier for the automations dialog\"},{\"name\":\"automationType\",\"type\":\"string\",\"doc\":\"and all other AutomationParticipant fields we want to keep for journey\"},{\"name\":\"connectionId\",\"type\":\"string\",\"doc\":\"the unique identifier for this appearance of this participant on this engagement\"},{\"name\":\"providerCallId\",\"type\":\"string\",\"doc\":\"the provider-native identifier for the call\"},{\"name\":\"joinedAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"doc\":\"Timestamp (milliseconds since epoch) the Agent joined the engagement\",\"default\":null},{\"name\":\"leftAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"doc\":\"Timestamp (milliseconds since epoch) the Agent left the engagement\",\"default\":null}]},{\"type\":\"record\",\"name\":\"AgentParticipant\",\"fields\":[{\"name\":\"id\",\"type\":\"string\",\"doc\":\"the unique identifier for the agent\"},{\"name\":\"channelProviderId\",\"type\":\"string\",\"doc\":\"the unique identifier for this engagement provider\"},{\"name\":\"providerDialogId\",\"type\":\"string\",\"doc\":\"the channelProviders identifier for the automations dialog\"},{\"name\":\"providerCallId\",\"type\":\"string\",\"doc\":\"the provider-native identifier for the call\"},{\"name\":\"connectionId\",\"type\":\"string\",\"doc\":\"the unique identifier for this appearance of this participant on this engagement\"},{\"name\":\"extension\",\"type\":\"string\",\"doc\":\"the agents extension/line\"},{\"name\":\"channelType\",\"type\":\"ChannelType\",\"doc\":\"the channelType of the engagement\"},{\"name\":\"invitedAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"doc\":\"Timestamp (milliseconds since epoch) the Agent was invited to the engagement (alerting)\",\"default\":null},{\"name\":\"joinedAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"doc\":\"Timestamp (milliseconds since epoch) the Agent joined the engagement\",\"default\":null},{\"name\":\"leftAt\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"doc\":\"Timestamp (milliseconds since epoch) the Agent left the engagement\",\"default\":null}]}]},\"doc\":\"List participants\",\"default\":[]},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Timestamp (milliseconds since epoch) the Engagement. Used for routing to correct Elasticsearch index\"}]}"} to http://kafka-cp-schema-registry:8081/subjects/com.company.avro.EngagementAggregate?deleted=true (io.confluent.kafka.schemaregistry.client.rest.RestService)
[2020-03-02 23:35:34,093] TRACE Putting [SinkRecord{kafkaOffset=0, timestampType=CreateTime} ConnectRecord{topic='engagement-astonmartin-202003', kafkaPartition=0, key=engId1, keySchema=Schema{STRING}, value=Struct{id=engId1,tenantId=astonmartin,identifiers={phoneNumber=[1122324]},conversations=[Struct{intent=foo}],participants=[Struct{ExternalParticipant=Struct{id=p1,callingNumber=1234,dialledNumber=123455,providerCallId=provider1,channelType=VOICE,joinedAt=Mon Mar 02 23:35:06 UTC 2020}}],timestamp=Mon Mar 02 23:35:06 UTC 2020}, valueSchema=Schema{STRING}, timestamp=1583192107463, headers=ConnectHeaders(headers=)}] to Elasticsearch. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask)
[2020-03-02 23:35:34,093] DEBUG Topic 'engagement-astonmartin-202003' was translated as index 'engagement-astonmartin-202003' (io.confluent.connect.elasticsearch.ElasticsearchWriter)
[2020-03-02 23:35:34,191] ERROR Can't convert record from topic engagement-astonmartin-202003 with partition 0 and offset 0. Error message: Invalid type for STRING: class org.apache.kafka.connect.data.Struct (io.confluent.connect.elasticsearch.ElasticsearchWriter)
```

**Comment by levzem** [comment]
@dkirrane what version of the connector are you using?

```
[2020-03-02 23:35:34,093] TRACE Putting [SinkRecord{kafkaOffset=0, timestampType=CreateTime} ConnectRecord{topic='engagement-astonmartin-202003', kafkaPartition=0, key=engId1, keySchema=Schema{STRING}, value=Struct{id=engId1,tenantId=astonmartin,identifiers={phoneNumber=[1122324]},conversations=[Struct{intent=foo}],participants=[Struct{ExternalParticipant=Struct{id=p1,callingNumber=1234,dialledNumber=123455,providerCallId=provider1,channelType=VOICE,joinedAt=Mon Mar 02 23:35:06 UTC 2020}}],timestamp=Mon Mar 02 23:35:06 UTC 2020}, valueSchema=Schema{STRING}, timestamp=1583192107463, headers=ConnectHeaders(headers=)}] to Elasticsearch. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask)
```

if you look at this log line you will notice that your record has the wrong schema
```
value=Struct{id=engId1,tenantId=astonmartin,identifiers={phoneNumber=[1122324]},conversations=[Struct{intent=foo}],participants=[Struct{ExternalParticipant=Struct{id=p1,callingNumber=1234,dialledNumber=123455,providerCallId=provider1,channelType=VOICE,joinedAt=Mon Mar 02 23:35:06 UTC 2020}}],timestamp=Mon Mar 02 23:35:06 UTC 2020}, valueSchema=Schema{STRING}
```

its value is `Struct`, but for some reason your valueSchema is `String`. I would make sure your data is clean first.

**Comment by dkirrane** [comment]
@levzem I'm using 5.3.1. 

Where does it get `valueSchema` from? From records itself?

Strange cause he record is built using builder from the avro-maven-plugin generated code.
I'm writing the record to topic with:
```
        EngagementAggregate records = EngagementAggregate
                   // fields here
                  .build();
        ProducerRecord<String, SpecificRecord> producerRecord = new ProducerRecord<>(topicName, id, record);
        myProducer.send(producerRecord);
```

I've set `RecordNameStrategy` on producer and connector config.

**Comment by levzem** [comment]
@dkirrane 
a ConnectRecord contains the fields `topic`, `kafkaPartition`, `kafkaOffset`, `key`, `keySchema`, `value`, and `valueSchema`. 

if the connector is receiving an incorrect record it must be somewhere on the producing or serializing side. I would check the serialization of the producer and just double check the contents of the record before you write it. But from what I can see, the `valueSchema` is set incorrectly.

**Comment by dkirrane** [comment]
@levzem a bit stumped on this..

I can produce and consume from my Topic with an Avro Producer & Avro Consumer.
I don't see anywhere in ProducerRecord where I have to explicitly set the Schema.

I've created a small 2 field Avro schema, and hit the same Connector issue `valueSchema=Schema{STRING}`
```
final FoodOrdered record = FoodOrdered.newBuilder()
        .setOrderId(id)
        .setTenantId(tenantId)
        .build();

ProducerRecord<String, SpecificRecord> producerRecord = 
                new ProducerRecord<>(TOPIC_NAME, null, timestamp, id, record);
this.producer.send(producerRecord);
```


My `AvroGenerated` `FoodOrdered` code _has the SCHEMA$ field_:
```java
@org.apache.avro.specific.AvroGenerated
public class FoodOrdered extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5600538396353188354L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FoodOrdered\",\"namespace\":\"com.playground.avro.schema.simple\",\"fields\":[{\"name\":\"orderId\",\"type\":\"string\"},{\"name\":\"tenantId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
....
```


My Producer config:
```
    private KafkaProducer<String, SpecificRecord> createProducer() {
        Properties props = new Properties();
        props.put(ProducerConfig.ACKS_CONFIG, "all");
        props.put(ProducerConfig.RETRIES_CONFIG, 0);
        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, bootstrapServers);

        /* https://docs.confluent.io/current/schema-registry/serializer-formatter.html */
        props.put(AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, schemaRegistryUrl);
        props.put(AbstractKafkaAvroSerDeConfig.AUTO_REGISTER_SCHEMAS, config.getKafka().getAutoRegisterSchemas());
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, SpecificAvroSerializer.class.getName());

        // Multi-schema topic = <fqdn>
        props.put(KafkaAvroSerializerConfig.VALUE_SUBJECT_NAME_STRATEGY, RecordNameStrategy.class.getName());
        // Single schema topic = <topic name>-value
        props.put(KafkaAvroSerializerConfig.VALUE_SUBJECT_NAME_STRATEGY, TopicNameStrategy.class.getName());

        KafkaProducer<String, SpecificRecord> kafkaProducer = new KafkaProducer<>(props);
        return kafkaProducer;
    }
```

**Comment by dkirrane** [comment]
So, my issue was a custom SMT dropping the schema. Closing
