### ISSUE TITLE
kafka to es pipeline not work.

### ISSUE THREAD

**Issue by yaphetsglhf** [confluentinc/kafka-connect-elasticsearch#399]
My data pipeline is from mysql to es. my kafka cluster can receive cdc events from mysql rightly, but my es can never get any messages.
 
First time, I write my es-sink.json like this:
```
{
    "name": "elastic-sink",
    "config": { 
		"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector", 
		"errors.log.enable": "true", 
		"tasks.max": "1", 
		"topics": "mysql2es.main.test", 
		"connection.url": "http://es-elasticsearch-client:9200", 
		"transforms": "unwrap,key", 
		"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState", 
		"transforms.unwrap.drop.tombstones": "false", 
		"transforms.key.type": "org.apache.kafka.connect.transforms.ExtractField$Key", 
		"transforms.key.field": "id", 
		"key.ignore": "false", 
		"type.name": "_doc", 
		"behavior.on.null.values": "delete"
    }
}
```
when i post the restful api to add the connector, error happened:  
```
Invalid value io.debezium.transforms.ExtractNewRecordState for configuration transforms.unwrap.type: Class io.debezium.transforms.ExtractNewRecordState could not be found.\nInvalid value null for configuration transforms.unwrap.type: Not a Transformation\nYou can also find the above list of errors at the endpoint `/{connectorType}/config/validate`"
```

secondly, i changed my json file like this:
```
{
    "name": "elastic-sink",
    "config": { 
		"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector", 
		"errors.log.enable": "true", 
		"tasks.max": "1", 
		"topics": "mysql2es.main.test", 
		"connection.url": "http://es-elasticsearch-client:9200", 
		"key.ignore": "true", 
		"type.name": "_doc", 
		"behavior.on.null.values": "delete"
    }
}
```

I just deleted transfroms related configs, this time i added the connector successfully, but then another error happened:

```
2020-03-22 15:41:12,159 ERROR WorkerSinkTask{id=elastic-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover
until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask) [pool-4-thread-1]
org.apache.kafka.connect.errors.ConnectException: Key is used as document id and can not be null.
        at io.confluent.connect.elasticsearch.DataConverter.convertKey(DataConverter.java:82)
        at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:182)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.tryWriteRecord(ElasticsearchWriter.java:291)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:276)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:174)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:565)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:194)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
```

can someone help me? is there something I missed?

**Comment by yaphetsglhf** [comment]
Version info:
kafka: 2.4.0
es: 6.7.9
platform: k8s  installed by helm

**Comment by yaphetsglhf** [comment]
well, I reboot all my components, pipleline works in the second scene.  still attempting to figure out the reason in the first scene.

**Comment by levzem** [comment]
@yaphetsglhf looks like you are misconfiguring the SMT. This does not seem like an issue with ES. Please let me know if you have some questions or need some help.

**Comment by pavelpe** [comment]
Not related to your issue in first case, but I think setting configuration:
`"key.ignore": "true",`
`behavior.on.null.values": "delete"`
is meaningless, as your would never be able to delete previously indexed document.

**Comment by levzem** [comment]
closing but feel free to reopen if your issue still persists
