### ISSUE TITLE
kafka-connect-elasticsearch does not work with opendistro elasticsearch

### ISSUE THREAD

**Issue by agujrathi** [confluentinc/kafka-connect-elasticsearch#431]
Looks like the default configuration of opendistro not able to work with kafka-connect-elasticsearch connector.

It fails at...

`PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException`

By default the connector uses SSL certificates..
below is the configuration from kafka-connect-elasticsearch-connector

```
    name=elasticsearch-sink
    connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
    tasks.max=1
    topics=test-elasticsearch-sink
    key.ignore=true
    connection.url=https://localhost:9200
    type.name=kafka-connect
```

It asks for keys strictly and not finding which keys to be provided to get connected with elasticsearch.
opendistro elastic fails with error:

`    PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException`

Strange that there was not a single mention of this anywhere gooleing related to opendistro elastic connection... :(

Please let me know if this is an issue .. If not, please help on this the same to point to correct path and way to connect with..

This link says about re-generating keys.. but not sure how it would affect the existing work flow..
https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/security.html

Please advice if I can use same keys as in config folder.. generated with demo certificate.. and which keys to be used... in above config..

By default, the opendistro install demo certificate creates demo certificates and I am able to use opendistro properly no issues... connected kibana, logstash, etc..

But problem with connecting kafka-connect-elasticsearch ... 
Seems no option to bypass SSL certifciate there as like logstash..

```
I have 3 key files generated in opendistro elasticsearch

    root-ca.pem 
    esnode.pem 
    kirk.pem
```
Now sure which to use and how to use with kafka-connect-elasticsearch connector..

Is this an issue ??? 
If not, Not sure which to use with connector...
Please help guys... Terribly stuck here...

Thanks,
Abhishek

**Comment by agujrathi** [comment]
Whatever I do..., always below errors ..

```
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1323)
        ... 39 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
        at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)
        at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
        ... 45 more
[2020-08-03 00:15:10,293] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)
[2020-08-03 00:15:10,293] INFO Stopping ElasticsearchSinkTask (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:190)
```

As logstash can connect without certificate validation, same way not finding way for kafka-connect-elasticsearch connect to secured elasticsearch..

How to disable ssl verification ??

Here is the config...

```
name=elasticsearch-sink
#connector.class=org.apache.kafka.connect.file.FileStreamSinkConnector
#connector.class=ElasticsearchSinkConnector
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
#connection.url=https://localhost:9200
connection.url=https://localhost:9200
tasks.max=1
topics=bika
type.name=kafka-connect
connection.username="admin"
connection.password="admin"
elasticsearch.username="admin"
elasticsearch.password="admin"
ssl.client.auth=true
elasticsearch.ssl.verificationMode: none
ssl_certificate_verification: false
key.ignore=true
schema.ignore = true
topic.key.ignore = 'bika'

```
Always SSL details are sent.. and rejected by elasticsearch..

Terribly stuck in this... .. Please help resolving this...

**Comment by agujrathi** [comment]
As logstash & kibana can disable ssl verification check... so same way, which param is controlled the disable ssl verification in kafka-connect-elasticsearch.. ?

**Comment by levzem** [comment]
@agujrathi you are missing some important SSL configs 
I recommend following [this documentation](https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/security.html) to get it working properly

**Comment by levzem** [comment]
closing due to no reply, feel free to reopen if you still need help

**Comment by arefehtam** [comment]
Remember these things:
1- kafka-connect user shound access certification path
2- if using pem cerfiticatte, first convert it to jks via keytool 
3- if you receive "PKIX path building failed' error, check your certificate if you allow it by name or by ip, if name was set so you should enter FQDN  names in your elastic url such this:
"connection.url": "https://node-0.example.com:9200,https://node-1.example.com:9200"
also remember to set node-0.example.com and node-2.example.com in /etc/hosts in all of your kafka-connect nodes if you still have not set DNS server
