### ISSUE TITLE
Kafka Connect can't connect to Elastic Cloud on Kubernetes v1.2  

### ISSUE THREAD

**Issue by devendraap** [confluentinc/kafka-connect-elasticsearch#432]
Hi,

Following is my setup over Kubernetes:
- Confluent Operator confluent-operator v1.0.5. Using which I deployed following deployments:
   - Operator 
   - Kafka
   - Connector
   - Schema Registry
- Elastic over Cloud operator v1.2. Using which I deployed:
   - ElasticSearch
   - Kibana

Now I am trying to setup ElasticSearch as Sink for Kafka topics.
So I am sending POST request to Connector API with following configuration:
- "name": "elastic-search-logs-sink",
- "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
- "connection.url": "https://elastic-search-cluster-es-http.elastic-search-logs:9200",
- "connection.username": "elastic",
- "connection.password": "*********************",    
- "elastic.security.protocol": "SSL",
- "tasks.max": "1",
- "topics": "TOPIC_NAME",
- "type.name": "_doc",
- "key.ignore": "true",
- "key.converter": "io.confluent.connect.avro.AvroConverter",
- "key.converter.schema.registry.url": "http://schemaregistry.kafka.svc.cluster.local:8081",
-  "value.converter": "io.confluent.connect.avro.AvroConverter",
-  "value.converter.schema.registry.url": "http://schemaregistry.kafka.svc.cluster.local:8081"

But I am getting SSL SSLHandshakeException exception:
`[ERROR] 2020-07-29 07:07:06,265 [task-thread-elastic-search-logs-sink-0] org.apache.kafka.connect.runtime.WorkerTask doRun - WorkerSinkTask{id=elastic-search-logs-sink-0} Task threw an uncaught and unrecoverable exception
org.apache.kafka.connect.errors.ConnectException: Couldn't start ElasticsearchSinkTask due to connection error:
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:159)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:142)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:122)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:304)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:195)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:133)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:70)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:63)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.getServerVersion(JestElasticsearchClient.java:247)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:151)
	... 12 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 35 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 41 more`

Following are my question:
- How do I fix the above error considering that ElasticSearch doesn't allow HTTP and enforces HTTPS in future? 
- Is there any way to add certificates via Kubernetes secrets during deployments, since this might become recurring issue while setting up other connectors?

**Comment by devendraap** [comment]
I have currently found work around by disabling TLS for ElasticSearch endpoint using:

```
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-search-cluster
spec:
  version: 7.8.0
  nodeSets:
  - name: default
    count: {{ .Values.nodeCount }}
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  http:
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: "elastic-search-cluster"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
```

**Comment by devendraap** [comment]
I have currently found work around by disabling TLS for ElasticSearch endpoint using:

`apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-search-cluster
spec:
  version: 7.8.0
  nodeSets:
  - name: default
    count: {{ .Values.nodeCount }}
    config:
      node.master: true
      node.data: true
      node.ingest: true
    podTemplate:
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  http:
    tls:
      selfSignedCertificate:
        disabled: true
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 7.8.0
  count: 1
  elasticsearchRef:
    name: "elastic-search-cluster"
  http:
    tls:
      selfSignedCertificate:
        disabled: true
`

**Comment by levzem** [comment]
@devendraap unfortunately, currently the connector will only accept the path to the certificates. I am not aware of any other way of doing it.

**Comment by devendraap** [comment]
@levzem Do I need to create custom Connector image with SelfSigned certificates added to JKS?

**Comment by levzem** [comment]
@devendraap I do not know the details of setting up the connector on Kubernetes. Whatever pod the Connect worker (and connector) is running on will need to have those certificates on the file path. Unfortunately that is all I can help you with.

**Comment by strigona-worksight** [comment]
We added a custom script to our connector image that would look for any certificates in a folder and add them to a keystore in a known place and then use that in the elasticsearch connector.

```
if [ -d /ssl/es-certificates/ ]; then
  echo "Preparing truststore for connectors"
  # Add each certificate to the trust store
  mkdir -p /home/kafka
  STORE=/home/kafka/truststore.jks
  declare -i INDEX=0
  for CRT in /ssl/es-certificates/*.crt; do
    keytool -keystore $STORE -storepass "changeme" -noprompt -import -file $CRT -storetype JKS
    INDEX+=1
  done
  echo "Preparing truststore for connectors is complete"
fi
```

Note there is a `storepass` that you should probably change. The value is also needed in your connector config I believe.
