### ISSUE TITLE
Caused by: org.apache.kafka.connect.errors.DataException: Cannot infer mapping without schema

### ISSUE THREAD

**Issue by iamtodor** [confluentinc/kafka-connect-elasticsearch#436]
Hello,

I'm trying to insert raw twitter tweet into the elastic search via kafka-connect-elasticsearch.
I'm getting the following error:
<details>
<summary>Exception</summary>

```
[2020-08-24 18:31:07,730] INFO Index 'twitter_es' not found in local cache; checking for existence (io.confluent.connect.elasticsearch.jest.JestElasticsearchClient:323)
[2020-08-24 18:31:07,856] INFO Index 'twitter_es' exists in Elasticsearch; adding to local cache (io.confluent.connect.elasticsearch.jest.JestElasticsearchClient:329)
[2020-08-24 18:31:08,423] INFO Get mapping (type=_doc) for index 'twitter_es' (io.confluent.connect.elasticsearch.jest.JestElasticsearchClient:412)
[2020-08-24 18:31:08,572] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Cannot infer mapping without schema. (org.apache.kafka.connect.runtime.WorkerSinkTask:566)
org.apache.kafka.connect.errors.DataException: Cannot infer mapping without schema.
        at io.confluent.connect.elasticsearch.Mapping.inferMapping(Mapping.java:84)
        at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createMapping(JestElasticsearchClient.java:395)
        at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:66)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:265)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:174)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:326)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-08-24 18:31:08,574] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:186)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:568)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:326)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Cannot infer mapping without schema.
        at io.confluent.connect.elasticsearch.Mapping.inferMapping(Mapping.java:84)
        at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.createMapping(JestElasticsearchClient.java:395)
        at io.confluent.connect.elasticsearch.Mapping.createMapping(Mapping.java:66)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:265)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:174)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
        ... 10 more
[2020-08-24 18:31:08,577] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:187)
[2020-08-24 18:31:08,577] INFO Stopping ElasticsearchSinkTask (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:190)
[2020-08-24 18:31:08,583] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Revoke previously assigned partitions twitter.raw_tweets-2, twitter.raw_tweets-1, twitter.raw_tweets-0 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:292)
[2020-08-24 18:31:08,584] WARN WorkerSinkTask{id=elasticsearch-sink-0} Offset commit failed during close (org.apache.kafka.connect.runtime.WorkerSinkTask:386)
[2020-08-24 18:31:08,584] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Commit of offsets threw an unexpected exception for sequence number 2: null (org.apache.kafka.connect.runtime.WorkerSinkTask:263)
org.apache.kafka.connect.errors.ConnectException: Stopping
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor.throwIfStopping(BulkProcessor.java:278)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor.throwIfTerminal(BulkProcessor.java:296)
        at io.confluent.connect.elasticsearch.bulk.BulkProcessor.flush(BulkProcessor.java:359)
        at io.confluent.connect.elasticsearch.ElasticsearchWriter.flush(ElasticsearchWriter.java:335)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.flush(ElasticsearchSinkTask.java:180)
        at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:125)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:383)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.closePartitions(WorkerSinkTask.java:598)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1300(WorkerSinkTask.java:69)
        at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsRevoked(WorkerSinkTask.java:674)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.invokePartitionsRevoked(ConsumerCoordinator.java:297)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onLeavePrepare(ConsumerCoordinator.java:726)
        at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.close(AbstractCoordinator.java:950)
        at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.close(ConsumerCoordinator.java:872)
        at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2343)
        at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2310)
        at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:2260)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:168)
        at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:163)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:190)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2020-08-24 18:31:08,586] INFO [Consumer clientId=connector-consumer-elasticsearch-sink-0, groupId=connect-elasticsearch-sink] Member connector-consumer-elasticsearch-sink-0-08073a46-e7d9-4282-98fa-7ae4ef06fb34 sending LeaveGroup request to coordinator 192.168.31.138:9092 (id: 2147483647 rack: null) due to the consumer is being closed (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:979)
```

</details>

My `es.properties` is the following:

```
name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector

schemas.enable=false
schema.ignore=false
key.converter.schemas.enable=false
value.converter.schemas.enable=false

connection.url=url.bonsaisearch.net:443
connection.username=username
connection.password=pass

tasks.max=1
topics=twitter.raw_tweets
topic.index.map=twitter.raw_tweets:twitter_es
key.ignore=true
type.name=_doc
```

My `connect-standalone.properties` is the following:

```
bootstrap.servers=localhost:9092
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000
plugin.path=connectors
```

I've discovered https://www.confluent.io/blog/kafka-connect-deep-dive-converters-serialization-explained/#json-message-without-expected-schema-payload-structure and set `schemas.enable=false` but nothing helps.

I'm inserting json
<details>
  <summary>raw_record.json</summary>

```json
{
    "created_at": "Thu Aug 20 08:23:33 +0000 2020",
    "id": 1296362220729892865,
    "id_str": "1296362220729892865",
    "text": "@savethekids1991 @DrGW0 @voltairesghost1 @lakersblake2 @real_defender @realDonaldTrump You are FAR from a free thin\u2026 https:\/\/t.co\/5RweY21wHE",
    "display_text_range": [
        87,
        140
    ],
    "source": "\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
    "truncated": true,
    "in_reply_to_status_id": 1296342119297163264,
    "in_reply_to_status_id_str": "1296342119297163264",
    "in_reply_to_user_id": 960912551113506816,
    "in_reply_to_user_id_str": "960912551113506816",
    "in_reply_to_screen_name": "savethekids1991",
    "user": {
        "id": 16259258,
        "id_str": "16259258",
        "name": "TimeCr0ss",
        "screen_name": "Timecr0ss",
        "location": "Pale Blue Dot",
        "url": null,
        "description": "I have Castle Bravo as my cover because this is the mess we are in. Proudly not retweeted by Trump.",
        "translator_type": "none",
        "protected": false,
        "verified": false,
        "followers_count": 132,
        "friends_count": 272,
        "listed_count": 0,
        "favourites_count": 9023,
        "statuses_count": 4035,
        "created_at": "Fri Sep 12 17:19:12 +0000 2008",
        "utc_offset": null,
        "time_zone": null,
        "geo_enabled": false,
        "lang": null,
        "contributors_enabled": false,
        "is_translator": false,
        "profile_background_color": "C0DEED",
        "profile_background_image_url": "http:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
        "profile_background_image_url_https": "https:\/\/abs.twimg.com\/images\/themes\/theme1\/bg.png",
        "profile_background_tile": false,
        "profile_link_color": "0084B4",
        "profile_sidebar_border_color": "FFFFFF",
        "profile_sidebar_fill_color": "DDEEF6",
        "profile_text_color": "333333",
        "profile_use_background_image": true,
        "profile_image_url": "http:\/\/pbs.twimg.com\/profile_images\/1285516950450384897\/8KqwGjNT_normal.jpg",
        "profile_image_url_https": "https:\/\/pbs.twimg.com\/profile_images\/1285516950450384897\/8KqwGjNT_normal.jpg",
        "profile_banner_url": "https:\/\/pbs.twimg.com\/profile_banners\/16259258\/1595326109",
        "default_profile": false,
        "default_profile_image": false,
        "following": null,
        "follow_request_sent": null,
        "notifications": null
    },
    "geo": null,
    "coordinates": null,
    "place": null,
    "contributors": null,
    "is_quote_status": false,
    "extended_tweet": {
        "full_text": "@savethekids1991 @DrGW0 @voltairesghost1 @lakersblake2 @real_defender @realDonaldTrump You are FAR from a free thinker. You repeat exactly what Q or Trump say.",
        "display_text_range": [
            87,
            159
        ],
        "entities": {
            "hashtags": [],
            "urls": [],
            "user_mentions": [
                {
                    "screen_name": "savethekids1991",
                    "name": "Cody",
                    "id": 960912551113506816,
                    "id_str": "960912551113506816",
                    "indices": [
                        0,
                        16
                    ]
                },
                {
                    "screen_name": "DrGW0",
                    "name": "Graham Webb",
                    "id": 94197182,
                    "id_str": "94197182",
                    "indices": [
                        17,
                        23
                    ]
                },
                {
                    "screen_name": "voltairesghost1",
                    "name": "voltairesghost",
                    "id": 1254506116270219269,
                    "id_str": "1254506116270219269",
                    "indices": [
                        24,
                        40
                    ]
                },
                {
                    "screen_name": "lakersblake2",
                    "name": "Lakersblake2",
                    "id": 1274699127167660032,
                    "id_str": "1274699127167660032",
                    "indices": [
                        41,
                        54
                    ]
                },
                {
                    "screen_name": "real_defender",
                    "name": "RD",
                    "id": 49034507,
                    "id_str": "49034507",
                    "indices": [
                        55,
                        69
                    ]
                },
                {
                    "screen_name": "realDonaldTrump",
                    "name": "Donald J. Trump",
                    "id": 25073877,
                    "id_str": "25073877",
                    "indices": [
                        70,
                        86
                    ]
                }
            ],
            "symbols": []
        }
    },
    "quote_count": 0,
    "reply_count": 0,
    "retweet_count": 0,
    "favorite_count": 0,
    "entities": {
        "hashtags": [],
        "urls": [
            {
                "url": "https:\/\/t.co\/5RweY21wHE",
                "expanded_url": "https:\/\/twitter.com\/i\/web\/status\/1296362220729892865",
                "display_url": "twitter.com\/i\/web\/status\/1\u2026",
                "indices": [
                    117,
                    140
                ]
            }
        ],
        "user_mentions": [
            {
                "screen_name": "savethekids1991",
                "name": "Cody",
                "id": 960912551113506816,
                "id_str": "960912551113506816",
                "indices": [
                    0,
                    16
                ]
            },
            {
                "screen_name": "DrGW0",
                "name": "Graham Webb",
                "id": 94197182,
                "id_str": "94197182",
                "indices": [
                    17,
                    23
                ]
            },
            {
                "screen_name": "voltairesghost1",
                "name": "voltairesghost",
                "id": 1254506116270219269,
                "id_str": "1254506116270219269",
                "indices": [
                    24,
                    40
                ]
            },
            {
                "screen_name": "lakersblake2",
                "name": "Lakersblake2",
                "id": 1274699127167660032,
                "id_str": "1274699127167660032",
                "indices": [
                    41,
                    54
                ]
            },
            {
                "screen_name": "real_defender",
                "name": "RD",
                "id": 49034507,
                "id_str": "49034507",
                "indices": [
                    55,
                    69
                ]
            },
            {
                "screen_name": "realDonaldTrump",
                "name": "Donald J. Trump",
                "id": 25073877,
                "id_str": "25073877",
                "indices": [
                    70,
                    86
                ]
            }
        ],
        "symbols": []
    },
    "favorited": false,
    "retweeted": false,
    "filter_level": "low",
    "lang": "en",
    "timestamp_ms": "1597911813324"
}
```
</details>

Kafka version 2.5.0
Connector version 5.5.1

**Comment by moonshade** [comment]
@iamtodor How did you resolve this issue? I have the same issue now and would like to know about it, thanks!

**Comment by jliunyu** [comment]
Mett same issue as well! @iamtodor I'm also curious about how did you resolve this.
