### ISSUE TITLE
Error: Failed to check if index exists after upgrade to 11.0.0

### ISSUE THREAD

**Issue by drTr0jan** [confluentinc/kafka-connect-elasticsearch#481]
I've upgraded kafka-connect-elasticsearch from 10.0.2 to 11.0.0 and got an error.
Kafka Connect 2.6.0
ES 7.10.0
```
[2020-12-15 11:00:03,060] INFO Creating index syslog-201215. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:162)
[2020-12-15 11:00:04,795] ERROR WorkerSinkTask{id=elasticsearch-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Failed to check if index syslog-201215 exists. (org.apache.kafka.connect.runtime.WorkerSinkTask:586)
org.apache.kafka.connect.errors.ConnectException: Failed to check if index syslog-201215 exists.
        at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:357)
        at io.confluent.connect.elasticsearch.ElasticsearchClient.indexExists(ElasticsearchClient.java:291)
        at io.confluent.connect.elasticsearch.ElasticsearchClient.createIndex(ElasticsearchClient.java:181)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.ensureIndexExists(ElasticsearchSinkTask.java:163)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:90)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to check if index syslog-201215 exists
        at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:164)
        at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:120)
        at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:350)
        ... 15 more
```

**Comment by levzem** [comment]
@drTr0jan can you post the full stacktrace please?

**Comment by piraxis** [comment]
@levzem We get the same error after upgrading to VP 6.0.1 and using connector v11. This is what I get in the log:

`[2020-12-21 19:38:00,638] ERROR WorkerSinkTask{id=processingledger-s1-7-7-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Failed to check if index diagnostics.messages.proc
essingledger-s1 exists. (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.ConnectException: Failed to check if index diagnostics.messages.processingledger-s1 exists.
        at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:357)
        at io.confluent.connect.elasticsearch.ElasticsearchClient.indexExists(ElasticsearchClient.java:291)
        at io.confluent.connect.elasticsearch.ElasticsearchClient.createIndex(ElasticsearchClient.java:181)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.ensureIndexExists(ElasticsearchSinkTask.java:163)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:90)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to check if index diagnostics.messages.processingledger-s1 exists
        at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:164)
        at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:120)
        at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:350)
        ... 15 more
Caused by: java.io.IOException: Unrecognized SSL message, plaintext connection?
        at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:809)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:225)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
        at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433)
        at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1418)
        at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:782)
        at io.confluent.connect.elasticsearch.ElasticsearchClient.lambda$indexExists$4(ElasticsearchClient.java:293)
        at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:161)
        ... 17 more
Caused by: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
        at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:146)
        at java.base/sun.security.ssl.SSLEngineInputRecord.bytesInCompletePacket(SSLEngineInputRecord.java:64)
        at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:557)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:637)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:271)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:316)
        at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:509)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:120)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        ... 1 more`

**Comment by levzem** [comment]
@piraxis looks like an SSL issue. do you mind sharing your configurations?

**Comment by piraxis** [comment]
@levzem 

> --- 
processingledger-s1-7-7: 
  batch.size: 5000
  connection.url: "http://es-diag-data-hot.es-diag.svc.cluster.local:9200"
  connector.class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  flush.timeout.ms: 30000
  key.converter: org.apache.kafka.connect.storage.StringConverter
  key.ignore: true
  linger.ms: 5000
  max.buffered.records: 200000
  max.in.flight.requests: 1
  name: processingledger-s1-7-7
  read.timeout.ms: 10000
  schema.ignore: true
  tasks.max: 4
  topics: diagnostics.messages.processingledger-s1
  type.name: ""
  value.converter: io.confluent.connect.avro.AvroConverter
  value.converter.schema.registry.url: "http://REDACTED:8081"
  connection.username: REDACTED
  connection.password: REDACTED

**Comment by piraxis** [comment]
This works fine in 10.0.2 it throws that error in 11.

**Comment by levzem** [comment]
@piraxis works fine in v10.0.2 with CP 6.0.1?

so it looks like the connector is trying to use an SSL connection when it is not supposed to be.

would you mind also sharing some of the logs before the connector fails? preferably since starting up. There are some log messages pertaining to SSL I would like to see.

**Comment by piraxis** [comment]
@levzem yup. We just rolled back to 10.0.2 with 6.0.1 and it works fine. 
We rolled back so I got to check if I still have the logs since this was on our staging env.

**Comment by drTr0jan** [comment]
> @drTr0jan can you post the full stacktrace please and your configs?
```
[2020-12-22 12:44:16,453] INFO Creating index syslog-201222. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:162)
[2020-12-22 12:44:17,552] ERROR WorkerSinkTask{id=elasticsearch-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Failed to check if index syslog-201222 exists. (org.apache.kafka.connect.runtime.WorkerSinkTask:586)
org.apache.kafka.connect.errors.ConnectException: Failed to check if index syslog-201222 exists.
	at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:357)
	at io.confluent.connect.elasticsearch.ElasticsearchClient.indexExists(ElasticsearchClient.java:291)
	at io.confluent.connect.elasticsearch.ElasticsearchClient.createIndex(ElasticsearchClient.java:181)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.ensureIndexExists(ElasticsearchSinkTask.java:163)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to check if index syslog-201222 exists
	at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:164)
	at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:120)
	at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:350)
	... 15 more
Caused by: java.io.IOException: kafka_connect:pdEte0dzRJc7dhDsbCtu@10.10.20.72
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:809)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:225)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1418)
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:782)
	at io.confluent.connect.elasticsearch.ElasticsearchClient.lambda$indexExists$4(ElasticsearchClient.java:293)
	at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:161)
	... 17 more
Caused by: java.net.UnknownHostException: kafka_connect:pdEte0dzRJc7dhDsbCtu@10.10.20.72
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:800)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1495)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1354)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1288)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:664)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:635)
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:474)
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:221)
	... 23 more
[2020-12-22 12:44:17,555] ERROR WorkerSinkTask{id=elasticsearch-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:187)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:588)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:323)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:226)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to check if index syslog-201222 exists.
	at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:357)
	at io.confluent.connect.elasticsearch.ElasticsearchClient.indexExists(ElasticsearchClient.java:291)
	at io.confluent.connect.elasticsearch.ElasticsearchClient.createIndex(ElasticsearchClient.java:181)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.ensureIndexExists(ElasticsearchSinkTask.java:163)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:560)
	... 10 more
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to check if index syslog-201222 exists
	at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:164)
	at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:120)
	at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:350)
	... 15 more
Caused by: java.io.IOException: kafka_connect:pdEte0dzRJc7dhDsbCtu@10.10.20.72
	at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:809)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:225)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:212)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1433)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1418)
	at org.elasticsearch.client.IndicesClient.exists(IndicesClient.java:782)
	at io.confluent.connect.elasticsearch.ElasticsearchClient.lambda$indexExists$4(ElasticsearchClient.java:293)
	at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:161)
	... 17 more
Caused by: java.net.UnknownHostException: kafka_connect:pdEte0dzRJc7dhDsbCtu@10.10.20.72
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:800)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1495)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1354)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1288)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:664)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$InternalAddressResolver.resolveRemoteAddress(PoolingNHttpClientConnectionManager.java:635)
	at org.apache.http.nio.pool.AbstractNIOConnPool.processPendingRequest(AbstractNIOConnPool.java:474)
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:280)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.elasticsearch.client.RestClient.performRequest(RestClient.java:221)
	... 23 more
[2020-12-22 12:44:17,556] ERROR WorkerSinkTask{id=elasticsearch-connector-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:188)
[2020-12-22 12:44:17,559] INFO [Consumer clientId=connector-consumer-elasticsearch-connector-0, groupId=elasticsearch] Revoke previously assigned partitions syslog-3, syslog-2, syslog-1, syslog-0, syslog-7, syslog-6, syslog-5, syslog-4 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:307)
[2020-12-22 12:44:17,559] INFO [Consumer clientId=connector-consumer-elasticsearch-connector-0, groupId=elasticsearch] Member connector-consumer-elasticsearch-connector-0-c08a080e-c75a-4bbc-9f88-010966e6e7fa sending LeaveGroup request to coordinator 91.217.178.79:9093 (id: 2147483646 rack: null) due to the consumer is being closed (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:1005
```

```
{
 "name" : "elasticsearch-connector",
 "config" : {
  "connector.class" : "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
  "topics" : "syslog", 
  "tasks.max" : "1",
  "key.converter" : "org.apache.kafka.connect.storage.StringConverter",
  "value.converter" : "org.apache.kafka.connect.json.JsonConverter",
  "key.converter.schemas.enable" : "false",
  "value.converter.schemas.enable" : "false",
  "errors.retry.timeout" : "-1",
  "connection.url" : "https://kafka_connect:Passw0rD@127.0.0.1:9200",
  "key.ignore" : "true",
  "schema.ignore" : "true",
  "type.name" : "_doc",
  "elastic.security.protocol" : "SSL",
  "elastic.https.ssl.keystore.location" : "/usr/local/etc/kafka/tls/elasticsearch-keystore.p12",
  "elastic.https.ssl.keystore.password" : "passw0rd",
  "elastic.https.ssl.truststore.location" : "/usr/local/etc/kafka/tls/elasticsearch-truststore.p12",
  "elastic.https.ssl.truststore.password" : "passw0rd",
  "transforms":"routeTS",
  "transforms.routeTS.type":"org.apache.kafka.connect.transforms.TimestampRouter",
  "transforms.routeTS.topic.format":"${topic}-${timestamp}",
  "transforms.routeTS.timestamp.format":"yyMMdd"
 }
}
```

**Comment by levzem** [comment]
@drTr0jan since we are using the new rest client which takes an `HttpHost` instead of just the string for a url, I think this is the cause of the issue. I suggest to use `connection.password` and `connection.username` configurations to encode the password and username respectively instead of directly in the url. Also that way it won't leak in the logs and stack traces

Let me know if that works for you.

**Comment by piraxis** [comment]
@levzem While I don't have the logs anymore, my stack trace was a different problem. That was a config issue where we had HTTPS instead of HTTP in the URL. 

I'll try to roll that upgrade out again to get the full stacktrace, but the original stack posted with the 'Failed to check if index exists' message is the one we got when we used the correct config.

**Comment by drTr0jan** [comment]
@levzem it seems that it works correctly. Thx!

**Comment by levzem** [comment]
@piraxis sorry, a little confused. what are the actual configs and what is the actual stacktrace/problem? Mind posting them again?

**Comment by levzem** [comment]
closing due to no response, please reopen if there are still issues

**Comment by srujankujmar** [comment]
Getting the same error from our end too 

ERROR WorkerSinkTask{id=elasticsearch-connector-3} Task threw an uncaught and un
recoverable exception. Task is being killed and will not recover until manually restarted. Error: Failed to check if i
ndex count-test exists. (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-elastics
earch-connector-3]
org.apache.kafka.connect.errors.ConnectException: Failed to check if index count-test exists.
at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:360)
at io.confluent.connect.elasticsearch.ElasticsearchClient.indexExists(ElasticsearchClient.java:285)
at io.confluent.connect.elasticsearch.ElasticsearchClient.createIndex(ElasticsearchClient.java:184)
at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.ensureIndexExists(ElasticsearchSinkTask.java:163)
at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:90)
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:581)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:182)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:231)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.ConnectException: Failed to check if index count-test exists
at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:164)
at io.confluent.connect.elasticsearch.RetryUtil.callWithRetries(RetryUtil.java:120)
at io.confluent.connect.elasticsearch.ElasticsearchClient.callWithRetries(ElasticsearchClient.java:353)
... 15 more
Caused by: java.net.SocketTimeoutException: 3,000 milliseconds timeout on connection http-outgoing-29 [ACTIVE]
at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:789


Used the below conf

tasksMax: 3
class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
config:

connection.url: elasticsearch.es.amazonaws.com:7200
topics: count-test-topic
type.name: _doc
value.converter: io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url: https://schema-registry:8081
value.converter.schemas.enable: true
key.ignore: true
behavior.on.malformed.documents: IGNORE
behavior.on.null.values: IGNORE
drop.invalid.message: true
schema.ignore: true
proxy.host: proxy.internal.com
proxy.port: 6060
transforms: "dropPrefix"
transforms.dropPrefix.type: "org.apache.kafka.connect.transforms.RegexRouter"
transforms.dropPrefix.regex: "count-test-topic"
transforms.dropPrefix.replacement: "count-test"
value.converter.schema.registry.ssl.truststore.location: /opt/truststore.jks
value.converter.schema.registry.ssl.truststore.password: xxxxxxx
value.converter.schema.registry.ssl.keystore.location: /opt/keystore.jks
value.converter.schema.registry.ssl.keystore.password: xxxxxxx
value.converter.schema.registry.ssl.key.password: xxxxxxxxx


Could you please do the needful at the earliest
