### ISSUE TITLE
Kafka->Elastic->Connector: index_not_found_exception issue while running the curl on the topic index.

### ISSUE THREAD

**Issue by vperi1730** [confluentinc/kafka-connect-elasticsearch#482]
Hi Team,

I am working on a use case of writing content from Kafka to Elastic using the Kafka elastic connector plugin. With the following configuration in place, I am receiving a strange error on the index.

```
{
    "name": "elk-kafka-test1",
    "config": {
        "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
        "tasks.max": "1",
        "topics": "tdec16",
        "topic.index.map": "tdec16:tdec16_index",
        "connection.url": "https://localhost:9200",
        "type.name": "_doc",
        "key.ignore":"true",
        "schema.ignore":"true",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false"
    }
}
```

Upon executing the following statement, facing some index issue.

```
curl -u "elastic:$PASSWORD" -k -XGET https://localhost:9200/tdec16_index/_search?pretty
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index [tdec16_index]",
        "resource.type" : "index_or_alias",
        "resource.id" : "tdec16_index",
        "index_uuid" : "_na_",
        "index" : "tdec16_index"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index [tdec16_index]",
    "resource.type" : "index_or_alias",
    "resource.id" : "tdec16_index",
    "index_uuid" : "_na_",
    "index" : "tdec16_index"
  },
  "status" : 404
```

Need help to resolve this. There was one old issue #78, but didn't really get what was the resolution and i see it is in closed status.

**Comment by vperi1730** [comment]
I was able to resolve the index issue, however, the elastic search hits array is empty. Any thoughts on why is this behaviour?

**Comment by levzem** [comment]
@vperi1730 what version of the connector are you using and are there any error messages in the logs?

**Comment by vperi1730** [comment]
Hi @levzem, Issue is resolved now, There was some issue at my end w.r.t Kafkaconnect. Thanks for your help.

I am facing another challenge now where my use case is to pass the data from Kafka to ES over TLS. Hence for this, i am following the security blog which confluent has provided.  

https://docs.confluent.io/kafka-connect-elasticsearch/current/security.html

Following is my JSON configuration.

```
{
    "name": "elk-kafka-dec22-tlscrt",
    "config": {
        "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
        "tasks.max": "20",
        "topics": "tdec22",
	"topics.index.map": "tdec22:tdec22_i0",
        "connection.url": "https://elasticsearch-tls-es-http:9200",
	"connection.username": "elastic",
	"connection.password": "yw0L79K92b9D1iBg70kCYO1j",
        "type.name": "_doc",
	"key.ignore": "true",
	"schema.ignore": "true",
	"value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": "false",
	"elastic.security.protocol": "SSL",
	"elastic.https.ssl.keystore.location": "/usr/share/elasticsearch/config/certs/keystore.p12",
	"elastic.https.ssl.keystore.password": "1234567",
	"elastic.https.ssl.key.password": "1234567",
	"elastic.https.ssl.keystore.type": "PKCS12",
	"elastic.https.ssl.truststore.location": "/usr/share/elasticsearch/config/certs/truststore.p12",
	"elastic.https.ssl.truststore.password": "1234567",
	"elastic.https.ssl.truststore.type": "PKCS12",
	"elastic.https.ssl.protocol": "TLS"
    } 
}
```

When my Kafka connect is loading this JSON configuration, it is throwing me a continuous error on failed to load SSL Keystore.

```
org.apache.kafka.common.KafkaException: Failed to load SSL keystore /usr/share/elasticsearch/config/certs/keystore.p12 of type PKCS12
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$SecurityStore.load(DefaultSslEngineFactory.java:306)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$SecurityStore.<init>(DefaultSslEngineFactory.java:285)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createKeystore(DefaultSslEngineFactory.java:255)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:139)
	at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:136)
	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:93)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.configureSslContext(JestElasticsearchClient.java:247)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.getClientConfig(JestElasticsearchClient.java:203)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:159)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:152)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:74)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:48)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:302)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/config/certs/keystore.p12
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:155)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory$SecurityStore.load(DefaultSslEngineFactory.java:299)
```

The question here is, where do these trust and Keystore should go into. My understanding is, they should be inside the elastic search pod under the home directory. 

Need your valuable inputs here.

**Comment by levzem** [comment]
@vperi1730 
the keystore and truststore need to be present both on the ES pod AND the configured directory on the connector pod

**Comment by vperi1730** [comment]
Ok sure. Could you please check the attached log and let me know why my connector is getting killed/stopped and how can i make it continuously running?
[connector_stopped.txt](https://github.com/confluentinc/kafka-connect-elasticsearch/files/5734643/connector_stopped.txt)

**Comment by levzem** [comment]
@vperi1730 these logs dont tell me much besides that the connector is being started correctly and then being shutdown

I see, `2020-12-23 10:29:40,544 INFO Stopping connector elk-kafka-dec23-tlscrt (org.apache.kafka.connect.runtime.Worker) [DistributedHerder-connect-1-1]`

are you stopping the connector? otherwise it might be a kafka isse

**Comment by levzem** [comment]
closing due to no response, feel free to reopen if there are still issues
