### ISSUE TITLE
Worker task dies because uncaught exception

### ISSUE THREAD

**Issue by mdespriee** [confluentinc/kafka-connect-elasticsearch#502]
One of our production worker tasks failed with the following exception:
```
WorkerSinkTask{id=legacy-measures-elastic-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Bulk request failed.
```
and 
```
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:614)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
[...]
Caused by: org.apache.kafka.connect.errors.ConnectException: Bulk request failed.
	at io.confluent.connect.elasticsearch.ElasticsearchClient$1.afterBulk(ElasticsearchClient.java:336)
	at org.elasticsearch.action.bulk.BulkRequestHandler$1.onFailure(BulkRequestHandler.java:76)
	at org.elasticsearch.action.bulk.Retry$RetryHandler.onFailure(Retry.java:122)
[...]
Caused by: java.net.ConnectException: Timeout connecting to [240a2258fa6643a5a795d3380384f2fa.eu-central-1.aws.cloud.es.io/3.127.228.159:9243]
```

The connector is configured with the following params:
errors.tolerance=all
max.retries=100

But clearly there has been no retry whatsoever...

The underlying cause could only be a very transient network error, as the Elastic cluster is healthy. But even with a non healthy network or cluster, I don't expect kafka-connect to give up like this.

Versions:
- kafka-connect  from confluentinc/cp-kafka-connect-base:6.1.0
- elastic connector 11.0.1

**Comment by akshay0709** [comment]
By looking at the code, I think it's doing what its supposed to: https://github.com/confluentinc/kafka-connect-elasticsearch/blob/131ddc77b964190137a61826c9044f4830771b32/src/main/java/io/confluent/connect/elasticsearch/ElasticsearchClient.java#L336

It failed at ^ line. If you need to retry that you will have to replace the ```ConnectException``` with  retry-able one

**Comment by levzem** [comment]
looks like the client does not retry network errors like it should, this PR should address this issue https://github.com/confluentinc/kafka-connect-elasticsearch/pull/513

**Comment by levzem** [comment]
`v11.0.4` is available now containing the fix
