### ISSUE TITLE
Distributed mode and versionning

### ISSUE THREAD

**Issue by bquartier** [confluentinc/kafka-connect-elasticsearch#51]
Hi,

While running kafka-connect-elasticsearch in distributed mode, we get a lot of warnings about version conflicts:
`WARN Ignoring version conflicts for items: [Key{access-logs/from-kafka/normalized-logs+0+7542000}, Key{access-logs/from-kafka/normalized-logs+0+7542001}, Key{access-logs/from-kafka/normalized-logs+0+7542002} (...)`
Then, if I check one of the document in elasticsearch, I have:
```
$ curl 'localhost:9200/access-logs/from-kafka/normalized-logs%2B0%2B7542000?pretty=true'
{
  "_index" : "access-logs",
  "_type" : "from-kafka",
  "_id" : "normalized-logs+0+7542000",
  "_version" : 7542000,
  "found" : true,
  "_source" : {
   ...

```
were the version number (which, from the elasticsearch documentation is the number of versions) is equal to the offset in the partition (key.ignore=true in our configuration). This is unexpected and difficult to understand.

This is the configuration used to setup kafka-connect-elasticsearch:
```
$ curl -XPOST -H 'Content-Type: application/json' kafka-connect:8083/connectors -d '{
"name": "kafka-connect-elasticsearch-alogs",
"config": {
"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
"tasks.max": "3",
"topic.index.map": "normalized-logs:access-logs",
"schema.ignore": true,
"key.ignore": true,
"topics": "normalized-logs",
"connection.url": "http://elasticsearch:9200",
"type.name": "from-kafka"
}}'
```

Any idea why we get such a strange result?

Is it just too early to use the kafka-connect-elasticsearch connector in distributed mode?

(by the way, we index in elasticsearch 5, which is not officially supported by the jest client (but the index api didn't change)).

**Comment by shikhar** [comment]
That's a good point that when using `key.ignore=true` having the offset as ES document version is not useful since the topic/partition/offset is already encoded in the key.

Can you elaborate on 'lots of warnings'. I would expect some warnings when the connector is being rebalanced or when you are just starting, but they should not be persistent.

**Comment by shikhar** [comment]
`INFO` or `DEBUG` for this log line may be more appropriate in retrospect.

**Comment by simplesteph** [comment]
Seeing the same issue in a similar setup.
The triggering line error is:

```
[2017-01-06 04:59:58,458] ERROR Commit of WorkerSinkTask{id=elasticsearch-topic-0} offsets threw an unexpected exception:  (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.ConnectException: Flush timeout expired with unflushed records: 560
	at io.confluent.connect.elasticsearch.bulk.BulkProcessor.flush(BulkProcessor.java:302)
	at io.confluent.connect.elasticsearch.ElasticsearchWriter.flush(ElasticsearchWriter.java:217)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.flush(ElasticsearchSinkTask.java:125)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:287)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:157)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Which is very odd...
Then I'm getting all these warnings. 

PS: How can I benefit from the elasticsearch connector updates if I'm using the cp-docker-images ?

**Comment by bquartier** [comment]
@shikhar Sorry for the very long delay, I didn't notice the notification...

By 'lots of warning' I meant thousands or warnings. not just a few when starting the connector when the shutdown was not clean.
Right now, we don't use the kafka elasticsearch connector anymore, so I am not sure I can help moving on with this issue.

My current hypothesis is that the connector was reading to many items from kafka and was not able to index them into elasticsearch before the session.timeout.ms triggered. The commit fails (because it is too late) and the items are given to another thread. However, part of them are already indexed.
(Not 100% sure, but it is the problem we hit with logstash and the kafka input plugin and elasticsearch output plugin).

Because i will not be able to help test any solution right now, from my point of view, you can close this issue.
