### ISSUE TITLE
Java class class java.util.Date does not have corresponding schema type

### ISSUE THREAD

**Issue by denzhel** [confluentinc/kafka-connect-elasticsearch#519]
Hi,

I'm using cp-kafka-connect 5.5.0 with the latest kafka-connect-elasticsearch plugin and Elasticearch 7
When trying to create a field and convert it from Epoch to Timestamp I get this message
```
[2021-05-07 15:21:36,346] ERROR WorkerSinkTask{id=rawpayload-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: Java class class java.util.Date does not have corresponding schema type. (org.apache.kafka.connect.runtime.WorkerSinkTask)
org.apache.kafka.connect.errors.DataException: Java class class java.util.Date does not have corresponding schema type.
	at org.apache.kafka.connect.json.JsonConverter.convertToJson(JsonConverter.java:614)
	at org.apache.kafka.connect.json.JsonConverter.convertToJson(JsonConverter.java:678)
	at org.apache.kafka.connect.json.JsonConverter.convertToJsonWithoutEnvelope(JsonConverter.java:585)
	at org.apache.kafka.connect.json.JsonConverter.fromConnectData(JsonConverter.java:335)
	at io.confluent.connect.elasticsearch.DataConverter.getPayload(DataConverter.java:186)
	at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:147)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.tryWriteRecord(ElasticsearchSinkTask.java:187)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:92)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:546)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:326)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This is my config:
```
          "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
          "connection.url": "http://elasticsearch7:9200",
          "tasks.max": "1",
          "topics.regex": "consumer.*.alerts",
          "name": "rawpayload",
          "type.name": "_doc",
          "value.converter": "org.apache.kafka.connect.json.JsonConverter",
          "value.converter.schemas.enable": "false",
          "schema.ignore": "true",
          "key.ignore": "true",
          "errors.tolerance": "all",
          "transforms": "dropPrefix,routeTS,InsertField,insertTS,convertTS",
          "transforms.dropPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
          "transforms.dropPrefix.regex": "consumer[.](.*)[.]alerts",
          "transforms.dropPrefix.replacement": "$1",
          "transforms.routeTS.type": "org.apache.kafka.connect.transforms.TimestampRouter",
          "transforms.routeTS.timestamp.format": "yyyy.dd.MM",
          "transforms.routeTS.topic.format": "rawpayload-${topic}-${timestamp}",
          "transforms.InsertField.type": "org.apache.kafka.connect.transforms.InsertField$Value",
          "transforms.InsertField.static.field": "application",
          "transforms.InsertField.static.value": "rawpayload",
          "transforms.insertTS.type"           : "org.apache.kafka.connect.transforms.InsertField$Value",
          "transforms.insertTS.timestamp.field": "@timestamp",
          "transforms.convertTS.type"            : "org.apache.kafka.connect.transforms.TimestampConverter$Value",
          "transforms.convertTS.format"          : "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
          "transforms.convertTS.field"           : "@timestamp",
          "transforms.convertTS.target.type"     : "Timestamp"
```

**Comment by denzhel** [comment]
If anyone else will encounter this, I found a solution.

You have to use an exact format or else you'd end up with the above error.
The formats can be found here:
https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html

In addition, the type has to be string:
```
          "transforms.convertTS.type"            : "org.apache.kafka.connect.transforms.TimestampConverter$Value",
          "transforms.convertTS.format"          : "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
          "transforms.convertTS.field"           : "@timestamp",
          "transforms.convertTS.target.type"     : "string"
```
