### ISSUE TITLE
Elasticsearch Sink Connector 3.1.1 and mapping problem for geo_point

### ISSUE THREAD

**Issue by totojack** [confluentinc/kafka-connect-elasticsearch#57]
Hi.

We're trying to migrate from Datamountaineer Elastic Sink connector to the official Confluent connector. We're experiencing problems with geo_point data types, correctly working with the previous connector, but obviously it depends on custom connector logic. This is the error, repeated for all points:

```
org.apache.kafka.connect.errors.ConnectException: Bulk request failed: [{"type":"mapper_parsing_exception","reason":"failed to parse [geoVal]","caused_by":{"type":"number_format_exception","reason":"For input string: \"43.54801,10.31061\""}}]
    at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.execute(BulkProcessor.java:353)
    at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:326)
    at io.confluent.connect.elasticsearch.bulk.BulkProcessor$BulkTask.call(BulkProcessor.java:312)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

This is the avro schema:

```
{"namespace": "com.streams.avro",
 "type": "record",
 "name": "Data",
 "fields": [
(...)
     {"name": "geoVal", "type": "string"},
(...)
 ]
}
```

This is the properties file content:

```
name=kafka-to-elasticsearch-connector
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=MYTOPIC
topic.index.map=MYTOPIC:myindex
key.ignore=true
topic.schema.ignore=MYTOPIC
connection.url=http://elasticsearch:9200
type.name=kafka-connect
```

This is the connector log initialization:

```
[2016-12-16 13:59:34,354] INFO Instantiated connector kafka-to-elasticsearch-measm-connector with version 3.1.1 of type class io.confluent.connect.elasticsearch.ElasticsearchSinkConnector (org.apache.kafka.connect.runtime.Worker)
[2016-12-16 13:59:34,356] INFO ElasticsearchSinkConnectorConfig values:
    batch.size = 2000
    connection.url = http://elasticsearch:9200
    flush.timeout.ms = 10000
    key.ignore = true
    linger.ms = 1
    max.buffered.records = 20000
    max.in.flight.requests = 5
    max.retries = 5
    retry.backoff.ms = 100
    schema.ignore = false
    topic.index.map = [MEASM-TOPIC:measm_by_sensor_param]
    topic.key.ignore = []
    topic.schema.ignore = [MEASM-TOPIC]
    type.name = kafka-connect
 (io.confluent.connect.elasticsearch.ElasticsearchSinkConnectorConfig)
[2016-12-16 13:59:34,357] INFO Finished creating connector kafka-to-elasticsearch-connector (org.apache.kafka.connect.runtime.Worker)
```

Ths is the field of elastic index:
```
(...)
          "geoVal": {
            "type": "geo_point"
          },
(...)
```

I'm not sure if it's an avro schema problem or if we're missing some configuration on properties file.

Thanks
Luca

**Comment by shikhar** [comment]
I will try to reproduce your issue, I don't notice any misconfiguration or incompatibility so there may be a bug.

**Comment by yaimag** [comment]
Hello, any updates on this issue?

**Comment by levzem** [comment]
@yaimag @totojack 

are you still affected by this?
