### ISSUE TITLE
Daily indices using TimestampRouter in 13.0.0+

### ISSUE THREAD

**Issue by tbnguyen1407** [confluentinc/kafka-connect-elasticsearch#633]
Hello, I could not find the changelog for 13.0.0 but it seems TimestampRouter is no longer supported

```
{
  ...
  "transforms": "tsRouter",
  "transforms.tsRouter.type": "org.apache.kafka.connect.transforms.TimestampRouter",
  "transforms.tsRouter.timestamp.format": "yyyy.MM.dd",
  "transforms.tsRouter.topic.format": "${topic}-${timestamp}",
  ...
}
```

```
[2022-05-18 02:19:50,287] ERROR WorkerSinkTask{id=esSnkConnector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:611)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:333)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.ConnectException: Found a topic name 'events-2022.05.18' that doesn't match assigned partitions. Connector doesn't support topic mutating SMTs
```

This was working with 11.1.10. What is expected way to create daily indices for 13.0.0+?

**Comment by OneCricketeer** [comment]
Use synchronous flushes

https://github.com/confluentinc/kafka-connect-elasticsearch/pull/589
