### ISSUE TITLE
org.apache.kafka.common.network.Mode has been renamed to org.apache.kafka.common.network.ConnectionMode

### ISSUE THREAD

**Issue by WGriffing** [confluentinc/kafka-connect-elasticsearch#819]
In https://github.com/apache/kafka/pull/16403 (referencing https://issues.apache.org/jira/browse/KAFKA-3346) `Mode` from `org.apache.kafka.common.network` was renamed to `ConnectionMode`.

As a result, I'm seeing this error

```
java.lang.NoClassDefFoundError: org/apache/kafka/common/network/Mode
```

when attempting to run version `14.1.2` of this plugin on kafka version `3.9.0`. `3.9.0` may not be supported (the [docs](https://docs.confluent.io/kafka-connectors/elasticsearch/current/overview.html#prerequisites) just say 3.3.0 or later) but I wanted to report this since I couldn't find any reference to it already being reported.

I am going to downgrade to a version prior to that change in kafka until this is resolved (or until that version is supported).

**Comment by srri** [comment]
I have also just started running into this myself.
```
2025-02-20 10:28:27 [2025-02-20 18:28:27,218] ERROR Failed to create client to verify connection.  (io.confluent.connect.elasticsearch.Validator)
2025-02-20 10:28:27 java.lang.NoClassDefFoundError: org/apache/kafka/common/network/Mode
2025-02-20 10:28:27     at io.confluent.connect.elasticsearch.ConfigCallbackHandler.sslContext(ConfigCallbackHandler.java:261)
2025-02-20 10:28:27     at io.confluent.connect.elasticsearch.ConfigCallbackHandler.createConnectionManager(ConfigCallbackHandler.java:172)
2025-02-20 10:28:27     at io.confluent.connect.elasticsearch.ConfigCallbackHandler.customizeHttpClient(ConfigCallbackHandler.java:95)
2025-02-20 10:28:27     at org.elasticsearch.client.RestClientBuilder.createHttpClient(RestClientBuilder.java:320)
2025-02-20 10:28:27     at java.base/java.security.AccessController.doPrivileged(Unknown Source)
2025-02-20 10:28:27     at org.elasticsearch.client.RestClientBuilder.build(RestClientBuilder.java:283)
2025-02-20 10:28:27     at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:312)
2025-02-20 10:28:27     at org.elasticsearch.client.RestHighLevelClient.<init>(RestHighLevelClient.java:304)
2025-02-20 10:28:27     at io.confluent.connect.elasticsearch.Validator.createClient(Validator.java:479)
2025-02-20 10:28:27     at io.confluent.connect.elasticsearch.Validator.validate(Validator.java:114)
2025-02-20 10:28:27     at io.confluent.connect.elasticsearch.ElasticsearchSinkConnector.validate(ElasticsearchSinkConnector.java:80)
2025-02-20 10:28:27     at org.apache.kafka.connect.runtime.AbstractHerder.validateConnectorConfig(AbstractHerder.java:719)
2025-02-20 10:28:27     at org.apache.kafka.connect.runtime.AbstractHerder.lambda$validateConnectorConfig$3(AbstractHerder.java:579)
2025-02-20 10:28:27     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2025-02-20 10:28:27     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
2025-02-20 10:28:27     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2025-02-20 10:28:27     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2025-02-20 10:28:27     at java.base/java.lang.Thread.run(Unknown Source)
2025-02-20 10:28:27 Caused by: java.lang.ClassNotFoundException: org.apache.kafka.common.network.Mode
2025-02-20 10:28:27     at java.base/java.net.URLClassLoader.findClass(Unknown Source)
2025-02-20 10:28:27     at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
2025-02-20 10:28:27     at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:124)
2025-02-20 10:28:27     at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
2025-02-20 10:28:27     ... 18 more
```
When trying to apply this config:
```
curl -X POST http://localhost:8083/connector-plugins -H 'Content-Type: application/json' -d \
'{
  "name": "elasticsearch-sink",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "tasks.max": "1",
    "topics": "elasticsearchIdentificationEvent",
    "key.ignore": "true",
    "schema.ignore": "true",
    "connection.url": "https://elasticsearch:9200",
    "name": "elasticsearch-sink",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "data.stream.type": "logs",
    "data.stream.dataset": "events",
    "data.stream.timestamp.field": "@timestamp",
    "connection.username": "elastic",
    "connection.password": "elastic123",
    "input.data.format": "JSON",
    "elastic.security.protocol": "SSL",
    "elastic.https.ssl.truststore.location": "/usr/share/elasticsearch/config/certs/ca/ca.crt",
    "elastic.https.ssl.truststore.type": "PEM",
    "errors.tolerance": "all"
  }
}'
```

This used to work just fine and now produces this response:
```
{"error_code":400,"message":"Connector configuration is invalid and contains the following 1 error(s):\nFailed to create client to verify connection. org/apache/kafka/common/network/Mode\nYou can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`"}
```

**Comment by Hen0k** [comment]
Hi All,

I am also running kafka 3.9.0 with strimzi and facing this issue when deploying the elasticsearch sink. 

`Failed to create client to verify connection. org/apache/kafka/common/network/Mode`

**Comment by Hen0k** [comment]
This was resolved for me with the latest release of the connector. V15.0.0
