### ISSUE TITLE
kafka-connect : does it work with stringconverter

### ISSUE THREAD

**Issue by diwakar222** [confluentinc/kafka-connect-elasticsearch#90]
i was trying to use "org.apache.kafka.connect.storage.stringconverter" instead of json converter for following properties:

key.converter
value.converter

and it throws out exceptions :
Exception in thread "main" org.apache.kafka.common.config.ConfigException: Invalid value org.apache.kafka.connect.storage.stringconverter for configuration key.converter: Class org.apache.kafka.connect.storage.stringconverter could not be found.
        at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:690)
        at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:433)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:56)
        at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:63)
        at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:163)
        at org.apache.kafka.connect.runtime.standalone.StandaloneConfig.<init>(StandaloneConfig.java:43)
        at org.apache.kafka.connect.cli.ConnectStandalone.main(ConnectStandalone.java:69)

let me know if its possible to use string instead of json

**Comment by nagys007** [comment]
Hi Diwakar,

class names are case sensitive, 
```
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
```
... worked for me

Regards,
Slavo

**Comment by ewencp** [comment]
Yes, @nagys007 has what looks like the correct solution. More generally, most connectors will work with any `Converter`. Usually the only incompatibility is if the `Converter` doesn't support schemas but the connector requires it. I believe `StringConverter` should work fine with this connector.
